changes/bug25675
src/or/control.c

Add a missing lock acquisition around access to queued_control_events
in control_free_all().  Use the reassign-and-unlock strategy as in
queued_events_flush_all().  Fixes bug 25675.  Coverity found this bug,
but only after we recently added an access to
flush_queued_event_pending.

Fix CID 1433643

---

changes/ticket25290
src/or/config.c
src/or/geoip.c

Both in geoip_note_client_seen() and options_need_geoip_info(), switch from
accessing the options directly to using the should_record_bridge_info() helper
function.
Fixes #25290

Switch to use should_record_bridge_info()

---

changes/ticket25996
src/test/test_hs_client.c

This test, in test_client_pick_intro(), will have different coverage
depending on whether it selects a good intro point the first time or
whether it has to try a few times.  Since it produces the shorter
coverage with P=1/4, repeat this test 64 times so that it only
provides reduced coverage with P=1/2^128.  The performance cost is
negligible.
Closes ticket 25996.  This test was introduced in 0.3.2.1-alpha.

coverage: Repeat the test for avoiding failed intro points

---

.travis.yml
Makefile.am

When Travis CI runs make distcheck, test-suite.log doesn't exist in
the expected place.  Add a new make target to show this file and use
it when DISTCHECK=yes in .travis.yml.  Fixes bug 25814; bug not in any
released Tor.

Show test-suite.log for distcheck on Travis CI

---

changes/ticket25995
src/test/test.c

I'd prefer not to do this for randomized tests, but as things stand
with this test, it produces nondeterministic test coverage.
Closes ticket 25995; bugfix on 0.2.2.2-alpha when this test was
introduced.

Use a deterministic PRNG in test_circuit_timeout()

---

changes/ticket26014
src/or/voting_schedule.c
src/test/include.am
src/test/test.c
src/test/test.h
src/test/test_voting_schedule.c

This functionality was covered only accidentally by our voting-test
code, and as such wasn't actually tested at all.  The tests that
called it made its coverage nondeterministic, depending on what time
of day you ran the tests.
Closes ticket 26014.

Add unit test for ..get_start_of_next_voting_interval().

---

src/common/crypto.c
src/common/crypto_rand.c

Code movement for the refactoring for ticket 24658 didn't copy the
inclusion of sys/random.h, which is needed to get a prototype for
getentropy() on macOS 10.12 Sierra.  It also didn't copy the inclusion
of sys/syscall.h, which might prevent the getrandom() syscall from
being properly detected.  Move these inclusions.  Bug not in any
released Tor.

Restore sys/random.h inclusion for getentropy()

---

changes/ticket26008
src/test/test_workqueue.c

Our previous algorithm had a nonzero probability of picking no
events to cancel, which is of course incorrect.  The new code uses
Vitter's good old reservoir sampling "algorithm R" from 1985.
Fixes bug 26008; bugfix on 0.2.6.3-alpha.

Fix the selection of events to cancel in test_workqueue.c

---

src/or/main.c

Fixes bug 25981; bugfix on 96c5ac338a7df.  Bug not in any released
version of Tor.

Don't crash when closing a connection before initializing libevent

---

changes/ticket25994
src/test/test_channel.c

This change should make it impossible for the monotonic time to roll
over from one EWMA tick to the next during this test, and make it so
that this test never invokes scale_active_circuits() (which it
doesn't test).
(Earlier changes during the 0.3.4 series should make this call even
rarer than it was before, since we fixed #25927 and removed
cached_gettimeofday.  Because this test didn't update
cached_gettimeofday, the chance of rolling over a 10-second interval
was much higher.)
Closes ticket 25994; bugfix on 0.3.3.1-alpha when this test was
introduced.

Hold monotonic time constant during channel/outbound_cell test

---

changes/bug25756
src/or/connection.c
src/or/connection.h
src/or/networkstatus.c
src/or/networkstatus.h
src/test/log_test_helpers.h
src/test/test_routerlist.c

These are the patches for https://trac.torproject.org/projects/tor/ticket/25756

Improve tolerance for dirauths with skewed clocks

---

src/or/relay.c

Previously, we used the AF_UNSPEC check to represent valid connected cell
data as a result of the lack of return. This was incorrect.

Bug 26117: Move CIRC_BW field accounting.

---

changes/bug26156
src/common/aes.c

Apparently, even though I had tested on OpenSSL 1.1.1 with
no-deprecated, OpenSSL 1.1.0 is different enough that I should have
tested with that as well.
Fixes bug 26156; bugfix on 0.3.4.1-alpha where we first declared
support for this configuration.

Add a missing include to get the declaration of OPENSSL_1_1_API

---

changes/bug26116
src/common/crypto.c
src/test/test_crypto.c

Apparently, contrary to its documentation, this is how OpenSSL now
wants us to report an error.
Fixes bug 26116; bugfix on 0.2.5.16.

Return -1 from our PEM password callback

---

changes/bug25686_diagnostic
src/or/directory.c
src/or/router.c

There are a few reasons that relays might be uploading desciptors
without saying X-Desc-Gen-Reason:
1. They are running an old version of our software, before 0.3.2.stable.
2. They are not running our software, but they are claiming they
are.
3. They are uploading through a proxy that strips X-Desc-Gen-Reason.
4. They somehow had a bug in their software.
According to the 25686 data, 1 is the most common reason.  This
ticket is an attempt to diagnose case 4, or prove that case 4
doesn't actually happen.

Several attempts to diagnose ticket 25686

---

changes/bug26152
src/test/test_crypto.c

These tests would report errors, but wouldn't report the offending
strings.

Improve openssl_version tests with better messages

---

Makefile.am

Note that clippy is quite loud/obnoxious, as its name would imply.
This target isn't meant to run on CI, or even necessarily exit
cleanly.  It's merely a way for developers to check if they've made
any glaring mistakes, or done awkward things they might not have
otherwise realised.  We *can* configure it to be quieter in the
future, but it's probably not worth rabbitholing on.
* CLOSES #22156: https://bugs.torproject.org/22156

[#22156] build: Add `make clippy` option for Rust linting.

---

src/or/include.am

This patch fixes linking errors when compiling Tor with the dirauth
module disabled.
See: https://bugs.torproject.org/26418

Fix linker errors when building Tor.

---

changes/bug26415
src/rust/crypto/digests/sha2.rs
src/rust/crypto/lib.rs

The doctests for src/rust/crypto don't compile for multiple reasons,
including some missing exports and incorrect identifier paths.  Fixes
bug 26415; bugfix on 0.3.4.1-alpha.

Fix compilation of Rust crypto doctests

---

changes/bug25886
src/or/nodelist.c
src/or/routerlist.c
src/or/routerlist.h

Was asked for [here](https://trac.torproject.org/projects/tor/ticket/25886). This fails on Rust tests but the master Tor GitHub repo fails as well, and I did not modify Rust code.

Trac #25886: Make frac_nodes_with_descriptors() take and use for_direct_connect (Revision 3)

---

changes/ticket19979
src/common/crypto_hkdf.c
src/test/test_crypto.c

Also, stop supporting empty HKDF input key material
https://trac.torproject.org/projects/tor/ticket/19979

#19979: When possible, use RFC5869 HKDF implementation from OpenSSL

---

configure.ac
src/lib/string/compat_string.h

When we do redefine them, use inline functions instead of #define.
This fixes a latent code problem in our redefinition of these
functions, which was exposed by our refactoring: Previously, we
would #define strcasecmp after string.h was included, so nothing bad
would happen.  But when we refactored, we would sometimes #define it
first, which was a problem on mingw, whose headers contain
(approximately):
inline int strcasecmp (const char *a, const char *b)
{ return _stricmp(a,b); }
Our define turned this into:
inline int _stricmp(const char *a, const char *b)
{ return _stricmp(a,b); }
And GCC would correctly infer that this function would loop forever,
rather than actually comparing anything.  This caused bug 26594.
Fixes bug 26594; bug not in any released version of Tor.

Don't redefine str(n)casecmp on windows unless they're missing

---

.travis.yml
changes/ticket26560

Apparently we weren't building with either libcap or libseccomp on
Travis.  Install libcap-dev and libseccomp-dev in .travis.yml.  Closes
ticket 26560.

Add more optional packages to Travis

---

.travis.yml

Right now we're having trouble getting Rust builds to succeed if
fragile hardening is enabled.  Add new mandatory jobs to make sure at
least some Rust testing happens in Travis.
Fixes bug 26449; bug not in any released tor.

Add Travis jobs for non-hardened Rust

---

changes/bug26535.029
src/test/ntor_ref.py

Recent Python3 versions seem to require this on Windows.
Fixes bug 26535; bug introduced in f4be34f70d6f277a0f3f73e, which
was apparently intended itself as a Python3 workaround.

ntor_ref.py: pass only strings to subprocess.Popen

---

changes/bug26535.032
src/test/hs_ntor_ref.py

Recent Python3 versions seem to require this on Windows.
Fixes bug 26535; bug copied from ntor_ref.py on 0.3.1.1-alpha.

hs_ntor_ref.py: pass only strings to subprocess.Popen

---

changes/bug26568
src/or/connection.c

This reverts part of commit 6ed384b827dce21ea3a44b587, in order to
fix bug 26568.  Bugfix on 0.3.4.1-alpha.

Partially revert "Use tor_addr_from_getsockname() in several places"

---

src/app/include.am
src/core/include.am

It's needed by main.c
Fixes bug 26662; bug not in any released Tor.

Move ntmain.c into libtor-app again

---

src/test/test_rust.sh

Out-of-tree builds could fail to run the rust tests if built in
offline mode.  cargo expects CARGO_HOME to point to the .cargo
directory, not the directory containing .cargo.
Fixes bug 26455; bug not in any released tor.

Use correct CARGO_HOME in test_rust.sh

---

changes/bug26269
src/or/router.c

Fixes bug 26269; bugfix on c30be5a82d47328 in 0.2.8.2-alpha

Fix a GCC "potential null dereference" warning.

---

src/or/routerlist.c

When on a private network a single directory authority is explicitly
configured, allow that DA's instace of tor to pick itself as its own
DA, by having router_pick_dirserver_generic() set the PDS_ALLOW_SELF
flag when the list of potential sources contains only one element.
This would subsequently allow router_pick_trusteddirserver_impl() to
calculate is 'requreother' condition as 'false', enabling it to pick
itself as a valid DA candidate.
Fixes #25928
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>

Allow single DA if explicitly configured

---

changes/ticket26492
src/rust/protover/ffi.rs
src/rust/tor_allocate/tor_allocate.rs

https://trac.torproject.org/projects/tor/ticket/26492#comment:2

code  style improvements for src/rust/protover/ffi.rs

---

changes/bug26437
src/ext/tinytest.c

See: https://bugs.torproject.org/26437

Fix forking tests on Windows when there is a space in the path.

---

src/feature/nodelist/networkstatus.c

This patch adds two assertions in get_net_param_from_list() to ensure
that the `res` value is correctly within the range of the output domain.
Hopefully fixes Coverity CID #1415721, #1415722, and #1415723.
See: https://bugs.torproject.org/26780

Add checks in get_net_param_from_list() for valid output domain.

---

changes/bug26785
configure.ac
src/common/compress_zstd.c

Conditionalize the pragma that temporarily disables
-Wunused-const-variable.  Some versions of gcc don't support it.  We
need to do this because of an apparent bug in some libzstd headers.
Fixes bug 26785; bugfix on 0.3.2.11.

Don't disable an unsupported compiler warning [ticket 26785]

---

changes/bug27003
src/or/periodic.c
src/test/test_periodic_event.c

When we fixed 25939 in f7633c1fcaefe72bf97c001bab9062132c919996, we
introduced a call to rescan_periodic_events() from inside the onion
service logic. But this meant that we could rescan the event list --
thereby running event callbacks! -- from inside the hidden service code.
This could cause us to run some of our event callbacks from an
inconsistent state, if we were in the middle of changing options.
A related bug (#25761) prevented us from rescanning our periodic
events as appropriate, but when we fixed THAT one, this bug reared
its ugly head.
The fix here is that "enabling" an event should cause us to run it
from the event loop, but not immediately from the point where we
enable it.
Fixes bug 27003; bugfix on 0.3.4.1-alpha.

When enabling periodic events, schedule but don't run them immediately.

---

src/feature/control/control.c

For the bug report [here](https://trac.torproject.org/projects/tor/ticket/27075).

[Tor Trac #27075]: Fix typo in control_event_hs_descriptor_content()

---

changes/bug26948
src/or/main.c

We would usually call it through tor_cleanup(), but in some code
paths, we wouldn't. These paths would break restart-in-process,
since leaving fields uncleared would cause assertion failures on
restart.
Fixes bug 26948; bugfix on 0.3.3.1-alpha

Always call tor_free_all() when exiting tor_run_main()

---

changes/ticket26947
src/feature/api/tor_api.c
src/feature/api/tor_api.h
src/tools/tor_runner.c

Add a new function, tor_api_get_provider_version()

---

changes/bug18642
src/core/or/relay.c
src/feature/relay/dns.c
src/feature/relay/dns.h

For the bug report [here](https://trac.torproject.org/projects/tor/ticket/18642).

Tor Trac #18642: Teach the OOM handler about the DNS cache (Revision 2)

---

changes/bug26779
configure.ac
src/common/compat_threads.c
src/common/compat_threads.h

I hope that the debian clang maintainers will look at debian bug
903709 soon. But until they do, this should keep our users and our
CI happy on sid with clang.
Closes ticket 26779.

Detect broken stdatomic.h, and pretend that it isn't there at all

---

src/feature/control/control.c

For the bug report [here](https://trac.torproject.org/projects/tor/ticket/27216).

[Tor Trac #27216]: Fix typo in comment for getinfo_helper_current_time()

---

src/test/test_address.c

For the bug report [here](https://trac.torproject.org/projects/tor/ticket/27250).

[Tor Trac #27250]: Duplicate line '#include "lib/net/address.h' in src/test/test_address.c

---

changes/bug27236
src/or/nodelist.c

Previously, Tor would only check the exit flag. In small networks, Tor
could bootstrap once it received a consensus with exits, without fetching
the new descriptors for those exits.
After bootstrap, Tor delays descriptor fetches, leading to failures in
fast networks like chutney.
Fixes 27236; bugfix on 0.2.6.3-alpha.

Bootstrap: check the exit policy and flag on descriptors

---

src/feature/hs_common/shared_random_client.c
src/test/test_shared_random.c

Bug description: For each descriptor, its revision counter is the OPE
ciphertext of the number of seconds since the start time of its SRV value.
This bug caused us to confuse the SRV start time in the middle of the lifetime
of a descriptor in some edge-cases, which caused descriptor rejects.
Bug cause: The bug occurs when we fetch a 23:00 consensus after
midnight (e.g. at 00:08 when not all dirauths have fetched the latest 00:00
consensus). In that case, the voting schedule (which was used for SRV start
time calculation) would return a valid-after past-midnight, whereas our
consensus would be pre-midnight, and that would confuse the SRV start time
computation which is used by HS revision counters (because we would reset the
start time of SRV, without rotating descriptors).
Bug fix: We now …

Fix revision counter bugs caused by bad SRV start time computation.

---

changes/bug20874
src/app/config/config.c
src/core/or/policies.c
src/test/test_options.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/20874).

[Tor Trac #20874]: ReachableAddresses adds an extra reject *:* on every SAVECONF

---

src/feature/nodelist/routerparse.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/27388).

[Tor Trac  #27388]: is_extrainfo in comment of router_parse_list_from_string() should be want_extrainfo

---

src/feature/control/control.c

Sends the Tor controller the uptime in seconds.
Highly useful for monitoring purposes.
Accompanying update to torspec: https://github.com/ageis/torspec/commit/5508508c0083e06e3ab68cf0c6c1d9a9bfaee9e3

control: Add new 'uptime' message to GETINFO

---

src/tools/tor-resolve.c

Bugfix on 2f657a1416f2f81dd1be900269c4ae9bdb29f52d; bug not in
any Tor release.
https://trac.torproject.org/projects/tor/ticket/27618#ticket

#27618: Bugfix: sizeof(socklen) doesn't make sense when calling connect()

---

changes/bug27658
src/ext/tinytest.c

It's possible for a unit test to report success via its pipe, but to
fail as it tries to clean up and exit.  Notably, this happens on a
leak sanitizer failure.
Fixes bug 27658; bugfix on 0.2.2.4-alpha when tinytest was
introduced.

Check waitpid return value and exit status in tinytest.c

---

changes/ticket23846
configure.ac

Add an --enable-pic option for people who hack Tor into libraries

---

changes/bug21530
src/core/or/policies.c

For the bug report [here](https://trac.torproject.org/projects/tor/ticket/21530).

[Tor Trac #21530] Make ExitRelay 0 the default when there is no exit policy

---

changes/bug27708
src/or/config.c

Before 0.3.3.1-alpha, we would exit() in this case immediately.  But
now that we leave tor_main() more conventionally, we need to make
sure we restore things so as not to cause a double free.
Fixes bug 27708; bugfix on 0.3.3.1-alpha.

If options_act() fails, restore the previous value of global_options

---

changes/ticket27797
src/feature/nodelist/nodelist.c

It is not enough to look at protover for v3 rendezvous support but also we
need to make sure that the curve25519 onion key is present or in other words
that the descriptor has been fetched and does contain it.
Fixes #27797.

node: Make node_supports_v3_rendezvous_point() also check for the key

---

src/feature/dircache/directory.c
src/feature/hs/hs_client.c
src/feature/hs/hs_descriptor.c

If a tor client gets a descriptor that it can't decrypt, chances are that the
onion requires client authorization.
If a tor client is configured with client authorization for an onion but
decryption fails, it means that the configured keys aren't working anymore.
In both cases, we'll log notice the former and log warn the latter and the
rest of the decryption errors are now at info level.
Two logs statement have been removed because it was redundant and printing the
fetched descriptor in the logs when 80% of it is encrypted wat not helping.
Fixes #27550

hs-v3: Silence some logging for client authorization

---

changes/bug27728
src/lib/crypt_ops/crypto_rand.c
src/lib/crypt_ops/crypto_rand.h
src/test/test_hs_descriptor.c

Instead, have it call a mockable function.  We don't want
crypto_strongest_rand() to be mockable, since doing so creates a
type error when we call it from ed25519-donna, which we do not build
in a test mode.
Fixes bug 27728; bugfix on 0.3.5.1-alpha

Make crypto_strongest_rand() non-mockable

---

changes/bug27893
src/app/config/config.c
src/app/config/confparse.c
src/app/config/confparse.h
src/app/config/statefile.c
src/feature/dirauth/shared_random_state.c

When freeing a configuration object from confparse.c in
dump_config(), we need to call the appropriate higher-level free
function (like or_options_free()) and not just config_free().
This only happens with options (since they're the one where
options_validate allocates extra stuff) and only when running
--dump-config with something other than minimal (since
OPTIONS_DUMP_MINIMAL doesn't hit this code).
Fixes bug 27893; bugfix on 0.3.2.1-alpha.

Fix a memory leak in --dump-config

---

src/lib/crypt_ops/crypto_dh_nss.c

Allowing this didn't do any actual harm, since there aren't any
shared structures or leakable objects here.  Still, it's bad style
and might cause trouble in the future.
Closes ticket 27856.

Prevent duplicate initialization of NSS DH module

---

src/feature/hs/hs_client.c

For the bug report [here](https://trac.torproject.org/projects/tor/ticket/27962).

[Tor Trac #27962]: Newline missing between between hs_client_get_random_intro_from_edge() and hs_client_receive_introduce_ack()

---

.travis.yml
changes/ticket27738

Use the Travis Homebrew addon to install packages on macOS. The package
list is the same, but the Homebrew addon does not do a `brew update` by
default.
This makes builds faster, at the cost of using slightly older packages.
Implements ticket 27738.

bug27738-029 Travis: use the Homebrew addon

---

changes/bug27709
src/common/util_bug.h

On GCC and Clang, there's a feature to warn you about bad
conditionals like "if (a = b)", which should be "if (a == b)".
However, they don't warn you if there are extra parentheses around
"a = b".
Unfortunately, the tor_assert() macro and all of its kin have been
passing their inputs through stuff like PREDICT_UNLIKELY(expr) or
PREDICT_UNLIKELY(!(expr)), both of which expand to stuff with more
parentheses around "expr", thus suppressing these warnings.
To fix this, this patch introduces new macros that do not wrap
expr.  They're only used when GCC or Clang is enabled (both define
__GNUC__), since they require GCC's "({statement expression})"
syntax extension.  They're only used when we're building the
unit-test variant of the object files, since they suppress the
branch-prediction hints. …

Revise our assertion and bug macros to work with -Wparentheses

---

changes/ticket27849
src/or/main.c

It turns out that if _only_ the ControlPort is set and nothing else, tor would
simply not bootstrap and thus not start properly. Commit 67a41b63063370c2
removed that requirement for tor to be considered a "client".
Unfortunately, this made the mainloop enable basically nothing if only the
ControlPort is set in the torrc.
This commit now makes it that we also consider the ControlPort when deciding
if we are a Client or not. It does not revert 67a41b63063370c2 meaning
options_any_client_port_set() stays the same, not looking at the control port.
Fixes #27849.

mainloop: Set client role if ControlPort is set

---

src/feature/hs/hs_cell.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/28066).

[Tor Trac #28066]: Fix typo in comment for hs_cell_parse_introduce2()

---

changes/ticket28089
src/or/connection.c

Commit 488e2b00bf881b97bcc8e4bbe304845ff1d79a03 introduced an issue, most
likely introduced by a bad copy paste, that made us stop reading on the
connection if our write bandwidth limit was reached.
The problem is that because "read_blocked_on_bw" was never set, the connection
was never reenabled for reading.
This is most likely the cause of #27813 where bytes were accumulating in the
kernel TCP bufers because tor was not doing reads. Only relays with
RelayBandwidthRate would suffer from this but affecting all relays connecting
to them. And using that tor option is recommended and best practice so many
many relays have it enabled.
Fixes #28089.

conn: Stop writing when our write bandwidth limist is exhausted

---

changes/bug27800
src/or/nodelist.c
src/test/test_nodelist.c

Occasionally, key pinning doesn't catch a relay that shares an ed25519
ID with another relay.  Log the identity fingerprints and the shared
ed25519 ID when this happens, instead of making a BUG() warning.
Fixes bug 27800; bugfix on 0.3.2.1-alpha.

ticket 27800-033: Log more info for duplicate ed25519 IDs

---

changes/bug27800
src/feature/nodelist/nodelist.c
src/test/test_nodelist.c

Occasionally, key pinning doesn't catch a relay that shares an ed25519
ID with another relay.  Log the identity fingerprints and the shared
ed25519 ID when this happens, instead of making a BUG() warning.
Fixes bug 27800; bugfix on 0.3.2.1-alpha.

bug 27800-035: Log more info for duplicate ed25519 IDs

---

changes/bug21900
configure.ac
doc/tor.1.txt
src/feature/relay/dns.c
src/feature/relay/dns.h
src/test/test_dns.c

https://trac.torproject.org/projects/tor/ticket/21900

#21900: Fallback to local DNS when no other nameservers are known (2)

---

changes/bug27741
src/rust/protover/ffi.rs

This argument was added to match an older idea for the C api, but we
decided not to do it that way in C.
Fixes bug 27741; bugfix on 0.3.3.6 / TROVE-2018-005 fix.

Remove extraneous argument from Rust protover_compute_vote()

---

changes/ticket27995
src/feature/hs/hs_service.c

It won't be used if there are no authorized client configured. We do that so
we can easily support the addition of a client with a HUP signal which allow
us to avoid more complex code path to generate that cookie if we have at least
one client auth and we had none before.
Fixes #27995

hs-v3: Always generate the descriptor cookie

---

changes/ticket27838
src/feature/hs/hs_service.c

Before this commit, we would create the descriptor signing key certificate
when first building the descriptor.
In some extreme cases, it lead to the expiry of the certificate which triggers
a BUG() when encoding the descriptor before uploading.
Ticket #27838 details a possible scenario in which this can happen. It is an
edge case where tor losts internet connectivity, notices it and closes all
circuits. When it came back up, the HS subsystem noticed that it had no
introduction circuits, created them and tried to upload the descriptor.
However, in the meantime, if tor did lack a live consensus because it is
currently seeking to download one, we would consider that we don't need to
rotate the descriptors leading to using the expired signing key certificate.
That being said, this commit does …

hs-v3: Create desc signing key cert before uploading

---

changes/bug27948
src/test/bt_test.py

Treat backtrace test failures as expected on NetBSD, OpenBSD, and
macOS/Darwin, until we solve bug 17808.
(FreeBSD failures have been treated as expected since 18204 in 0.2.8.)
Fixes bug 27948; bugfix on 0.2.5.2-alpha.

27948-master: Treat backtrace test failures as expected on most BSD-derived systems

---

changes/bug27948
src/test/bt_test.py

Treat backtrace test failures as expected on NetBSD, OpenBSD, and
macOS/Darwin, until we solve bug 17808.
(FreeBSD failures have been treated as expected since 18204 in 0.2.8.)
Fixes bug 27948; bugfix on 0.2.5.2-alpha.

27948-029: Treat backtrace test failures as expected on most BSD-derived systems

---

changes/bug27963_timeradd
src/lib/thread/.may_include
src/lib/thread/compat_pthreads.c

OpenSolaris apparently doesn't have timeradd(), so we added a
replacement, but we weren't including it here after the big
refactoring in 0.3.5.1-alpha.
Fixes bug 27963; bugfix on 0.3.5.1-alpha.

Add timeval.h include to compat_pthreads.c for timeradd()

---

changes/ticket28077
src/rust/tor_util/strings.rs

Let's see what Travis says to this.
https://trac.torproject.org/projects/tor/ticket/28077

#28077: rust/tor_util: drop unsafe block in cstr!

---

.appveyor.yml
changes/ticket28318

Build tor on Windows Server 2012 R2 and Windows Server 2016 using
Appveyor's CI.
Closes ticket 28318.

Appveyor: Add Windows Server 2016 to tor's build matrix

---

changes/bug25885
src/core/or/circuitbuild.c
src/core/or/circuitbuild.h
src/test/test_circuitbuild.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/25885).

[Tor Trac #25885]: count_acceptable_nodes() would be more accurate using node_has_preferred_descriptor() 

---

changes/bug28245
configure.ac
src/common/tortls.c

Failing to do on clients was causing TLS 1.3 negotiation to fail.
Fixes bug 28245; bugfix on 0.2.9.15, when we added TLS 1.3 support.

Always declare groups when building with openssl 1.1.1 APIs

---

src/feature/rend/rendcache.c

For the PR [here](https://trac.torproject.org/projects/tor/ticket/28425).

[Tor Trac #28425]: Typo in comment for rend_cache_failure in feature/rend/rendcache.c: "usuable" should be "usable"

---

changes/bug28441
src/feature/nodelist/nodelist.c

Clients have ignored the Named flag since 0.3.2.
Fixes bug 28441; bugfix on 0.3.2.1-alpha.

28441: log: stop talking about the Named flag in log messages

---

changes/bug28524
src/feature/control/control.c

Reset the added bootstrap tracking state introduced by ticket 27169.
Fixes bug 28524; bugfix on 0.3.5.1-alpha.

bug28524 Update control_free_all() for #27169

---

.appveyor.yml
changes/ticket28459

Always show the configure and test logs, and upload them as build
artifacts, when building for Windows using Appveyor CI.
Implements 28459.

Appveyor: always show the logs, and upload them as build artifacts

---

src/test/test_rebind.py
src/test/test_rebind.sh

Fixes #28562.
While here, put the argument count test and usage message _before_ we
attempt to read from sys.argv.

Create a temporary directory for tor's DataDirectory in test_rebind.

---

.appveyor.yml
changes/ticket28574

This patch explicitly specifies the path to our OpenSSL dependency and
disables the installation of an external OpenSSL version and instead
uses the OpenSSL version available from the MinGW environments.
See: https://bugs.torproject.org/28574

#28574 for 0.3.4: Explicitly specify path to OpenSSL for Appveyor.

---

changes/bug28554
src/test/test_entrynodes.c

test_entry_guard_outdated_dirserver_exclusion leaks memory, and is
missing some unmocks.
Fixes 28554; bugfix on 0.3.0.1-alpha.

0.3.3 merge Test: Fix memory leaks and missing unmocks in entry guard tests

---

changes/bug28554
src/test/test_entrynodes.c

test_entry_guard_outdated_dirserver_exclusion leaks memory, and is
missing some unmocks.
Fixes 28554; bugfix on 0.3.0.1-alpha.

Test: Fix memory leaks and missing unmocks in entry guard tests

---

src/core/or/versions.c

Bugfix on 469f47ef8dc8b18104108f0437c860ec88fca6ad; bug not in any released
Tor version.
https://trac.torproject.org/projects/tor/ticket/28592

#28592: Try silencing Coverity false positive CID 1441482

---

changes/ticket28275
doc/tor.1.txt

Removing a ".auth" file revokes a client access to the service but the
rendezvous circuit is not closed service side because the service simply
doesn't know which circuit is for which client.
This commit notes in the man page that to fully revoke a client access to the
service, the tor process should be restarted.
Closes #28275

man: Document HSv3 client authorization revocation

---

changes/ticket24803
src/or/fallback_dirs.inc

Replace the 150 fallbacks originally introduced in Tor 0.3.3.1-alpha in
January 2018 (of which ~115 were still functional), with a list of
148 fallbacks (89 new, 59 existing, 91 removed) generated in
December 2018.
Closes ticket 24803.

Fallbacks: Update the hard-coded fallback list in December 2018

---

.appveyor.yml

Appveyor images are named after the Visual Studio version they contain.
But we compile using MinGW, not Visual Studio.
We use these images because they have different Windows versions.
Closes bug 28826.

035 Appveyor: Explain appveyor image names in the comments

---

changes/ticket28731
src/feature/control/control.c

Add the bootstrap tag name to the log messages, so people
troubleshooting connection problems can look up a symbol instead of a
number.  Closes ticket 28731.

ticket28731-035 Log bootstrap tag names

---

changes/ticket28853
src/core/or/policies.c

The old implementation did some funky out-of-order lexing, and
tended to parse every port twice if the %d-%d pattern didn't match.
Closes ticket 28853.

Rewrite the core of parse_short_policy() to be faster.

---

changes/ticket28883
src/test/test_rebind.py

Fixes bug 28883; bugfix on 0.3.5.4-alpha.

test_rebind: wait for tor to timeout, even if it is logging a lot

---

Makefile.am
changes/bug28568

But continue to run stem's unit and online tests during
"make test-stem-full".
Fixes bug 28568; bugfix on 0.2.6.3-alpha.

Stop running stem's unit tests as part of "make test-stem"

---

src/lib/process/process_win32.c
src/test/test_process_slow.c

I tried to run the test cases for process_t related code in a VM with limited amount of memory and where I also ran a "load heavy" task (compiled Tor with -jN in a while true loop) and made some discoveries:
1. The exit handler would sometimes be called *before* we received the "Broken Pipe" event from `ReadFileEx()`. We now wait until we have received EOF state for both standard out and error before we check whether the process have terminated.
2. We forgot to clean up the child process' end of the pipes after the process have been created.
3. There is no need to log ordinary "end of process" conditions as "warning" log severity.
4. We forgot to set `reached_eof` to true under certain pathological conditions. Together with (1) this could sometimes lead to an error in the slow tests where …

#28179 win32 robustness

---

changes/ticket28180
changes/ticket28846
src/feature/client/transports.c
src/feature/client/transports.h
src/feature/control/control.c
src/feature/control/control.h
src/test/test_pt.c

These patches does the following:
1. Make the `LOG` message use the new K/V parser and the `config_line_t` encoding format.
2. Add the `STATUS` message.

#28846 implementation

---

changes/ticket28912
src/or/main.c

Linked connections aren't woken up by libevent due to I/O but rather
artificially so we can, by chunks, empty the spooled object(s).
Commit 5719dfb48f87a54aeb5982ff03345303bc058ebb (in 0.3.4.1-alpha) made it
that the schedule_active_linked_connections_event would be only called once at
startup but this is wrong because then we would never go through again the
active linked connections.
Fortunately, everytime a new linked connection is created, the event is
activated and thus we would go through the active list again. On a busy relay,
this issue is mitigated by that but on a slower relays or bridge, a connection
could get stuck for a while until a new directory information request would
show up.
Fixes #28717, #28912

mainloop: Reactivate the linked connection event with a non empty list

---

changes/ticket28852
src/feature/dirparse/parsecommon.c

I believe we originally added this for "just in case" safety, but it
isn't actually needed -- we never copy uninitialized stack here.
What's more, this one memset is showing up on our startup profiles,
so we ought to remove it.
Closes ticket 28852.

Remove a needless memset() in get_token_arguments()

---

changes/ticket28879
src/feature/relay/dns.c

Also, turn an absent hostname into a BUG(), not a crash.
Found by scan-build.
Closes ticket 28879; bugfix on 0.1.2.7-alpha

Check hostname before using it in send_resolved_hostname_cell()

---

changes/bug28619
src/or/hs_service.c

Bug reported on tor-dev@ and here is the detail explanation of the issue:
https://lists.torproject.org/pipermail/tor-dev/2018-November/013558.html
Fixes bug #28619

hs-v3: Do not close RP circuits when deleting an ephemeral service

---

src/feature/control/control_bootstrap.c

The message for the "ap_conn_proxy" bootstrap status tag was missing
some text.  Fixes bug 28929.  Bug not in any released Tor.

bug28929 Fix typo in bootstrap message

---

changes/bug28995
src/lib/net/socketpair.c

Trac ticket: https://trac.torproject.org/projects/tor/ticket/28995
This replaces PR #631

Fix tor_ersatz_socketpair on IPv6-only systems

---

src/lib/net/socket.c
src/lib/net/socketpair.c

Add some details about IP family support, and point to
tor_socketpair() from tor_ersatz_socketpair().
Closes ticket 29015.

lib/net: improve the docs for tor_{ersatz_,}socketpair()

---

changes/bug29042
src/lib/crypt_ops/crypto_rsa.c

We log these messages at INFO level, except when we are reading a
private key from a file, in which case we log at WARN.
This fixes a regression from when we re-wrote our PEM code to be
generic between nss and openssl.
Fixes bug 29042, bugfix on 0.3.5.1-alpha.

Log more messages when failing to decode RSA keys

---

changes/bug29175_035
src/core/proto/proto_socks.c
src/test/test_socks.c

https://trac.torproject.org/projects/tor/ticket/29175

#29175: Allow empty username/password in SOCKS5 username/password auth message (0.3.5)

---

src/test/test_rendcache.c

Because the test is adding entries to the "rend_cache" directly, the
rend_cache_increment_allocation() was never called which made the
rend_cache_clean() call trigger that underflow warning:
rend_cache/clean: [forking] Nov 29 09:55:04.024 [warn] rend_cache_decrement_allocation(): Bug: Underflow in rend_cache_decrement_allocation (on Tor 0.4.0.0-alpha-dev 2240fe63feb9a8cf)
The test is still good and valid.
Fixes #28660

test: Fix a warning underflow in rend_cache/clean

---

changes/bug29161
changes/ticket28668
changes/ticket29160
src/lib/encoding/time_fmt.c
src/test/test_address.c
src/test/test_rendcache.c
src/test/test_util.c
src/test/testing_common.c

Fail any unit test that causes an unhandled LD_BUG or LOG_ERR

---

changes/bug29298
src/test/test_circuitpadding.c

Disable unstable circuit padding unittest.

---

src/test/include.am

For the ticket [here](https://trac.torproject.org/projects/tor/ticket/29519).

[Tor Trac #29519]: Tor from Git on FreeBSD: cc src/test/test-slow leads to "/usr/bin/ld: error: unable to find library -levent"

---

changes/bug29508
src/core/or/scheduler_kist.c

kist: When readding chans, check correct chan's sched_heap_idx

---

src/test/test_util.c

This test fails in some environments; since the code isn't used in
0.4.0, let's disable it for now.
Band-aid solution for #29534; bug not in any released Tor.

Mark map_anon_nofork test as skipped in 0.4.0

---

src/test/test_address.c

Fixes bug 29530, where the LOG_ERR messages were occurring when
we had no configured network, and so we were failing the unit tests
because of the recently-merged #28668.
Bug not in any released Tor.

Downgrade some LOG_ERR messages in the address/* tests to warnings

---

changes/ticket25110
src/app/config/config.c

[https://trac.torproject.org/projects/tor/ticket/25110](https://trac.torproject.org/projects/tor/ticket/25110)

#25110: Warn operators who set MyFamily that they must also set ContactInfo

---

changes/ticket25417
src/feature/control/control.c
src/feature/hs/hs_client.c
src/feature/hs/hs_client.h
src/feature/hs/hs_control.c
src/feature/hs/hs_control.h

For the bug [here](https://trac.torproject.org/projects/tor/ticket/25417).

[Tor Trac #25417]: HSFETCH support for v3 Hidden Services

---

changes/bug24338
src/feature/dirauth/voteflags.c

For the ticket [here](https://trac.torproject.org/projects/tor/ticket/24338).

[Tor Trac #24338]: DirAuths that have IPv6 addresses don't include them in their vote on themself

---

changes/ticket29435
scripts/test/coverage

It was looking for object files made with the old automake
directorations, but those changed when we split up our libraries.
Fixes bug 29435; bugfix on 0.3.5.1-alpha.

Fix coverage script.

---

changes/bug29145
src/test/test-memwipe.c

malloc_options needs to be declared extern (and declaring it extern
means we need to initialize it separately)
Fixes bug 29145; bugfix on 0.2.9.3-alpha
Signed-off-by: Kris Katterjohn <katterjohn@gmail.com>

Fix a compiler warning on OpenBSD

---

changes/bug29599
src/test/test_shared_random.c

Stop leaking parts of the shared random state in the shared-random unit
tests.
Fixes bug 29599; bugfix on 0.2.9.1-alpha.

29599 029: test/shared-random: Stop leaking shared random state in the unit tests

---

changes/bug29599
src/test/test_shared_random.c

0.3.3 merge with updated function names.

Bug29599 033: test/shared-random: Stop leaking shared random state in the unit tests

---

changes/ticket29553
scripts/maint/pre-commit.git-hook

- handle older source layout
- handle empty changes directories
- "set -e" so that  we exit if there's a problem.

Update pre-commit.git-hook for ticket 29553

---

changes/bug29562
src/feature/client/transports.c

This patch fixes a crash bug (assertion failure) in the PT subsystem
that could get triggered if the user cancels bootstrap via the UI in
TorBrowser. This would cause Tor to call `managed_proxy_destroy()` which
called `process_free()` after it had called `process_terminate()`. This
leads to a crash when the various process callbacks returns with data
after the `process_t` have been freed using `process_free()`.
We solve this issue by ensuring that everywhere we call
`process_terminate()` we make sure to detach the `managed_proxy_t` from
the `process_t` (by calling `process_set_data(process, NULL)`) and avoid
calling `process_free()` at all in the transports code. Instead we just
call `process_terminate()` and let the process exit callback in
`managed_proxy_exit_callback()` handle the …

Fix crash bug in PT subsystem.

---

changes/bug25113
src/test/test_util.c

On slow system, 1 msec between one read and the other was too tight. For
instance, it failed on armel with a 4msec gap:
https://buildd.debian.org/status/package.php?p=tor&suite=experimental
Increase to 10 msec for now to address slow system. It is important that we
keep this OP_LE test in so we make sure the msec/usec/nsec read aren't
desynchronized by huge gaps. We'll adjust again if we ever encounter a system
that goes slower than 10 msec between calls.
Fixes #25113

25113 029: test: Bump to 10 msec gap in the monotonic test

---

changes/bug24903
src/or/control.c

There was a nonfatal assertion in pathbias_should_count that would
trigger if onehop_tunnel was set, but the desired_path_length was
greater than 1.  This patch fixes that.  Fixes bug 24903; bugfix on
0.2.5.2-alpha.

24903 029: When extending a circuit's path length, clear onehop_tunnel.

---

changes/bug17357
src/feature/rend/rendservice.c

For the ticket [here](https://trac.torproject.org/projects/tor/ticket/17357).

[Tor Trac #17357]: rend_service_relaunch_rendezvous() ignores hs_service_requires_uptime_circ()

---

src/lib/malloc/map_anon.c
src/lib/malloc/map_anon.h
src/test/test_util.c

This test was previously written to use the contents of the system
headers to decide whether INHERIT_NONE or INHERIT_ZERO was going to
work.  But that won't work across different environments, such as
(for example) when the kernel doesn't match the headers.  Instead,
we add a testing-only feature to the code to track which of these
options actually worked, and verify that it behaved as we expected.
Closes ticket 29541; bugfix not on any released version of Tor.

Re-enable and fix unit test for nofork mappings

---

changes/ticket29060
src/test/test-network.sh

https://trac.torproject.org/projects/tor/ticket/29060

#29060: Fix shellcheck warnings in test-network.sh

---

changes/ticket29635
doc/tor.1.txt

https://trac.torproject.org/projects/tor/ticket/29635

#29635: manpage: fix formatting of example on quoting options with spaces

---

scripts/maint/git-merge-forward.sh
scripts/maint/git-pull-all.sh

Replace the "git pull" by one single "git fetch origin" and then "git merge"
into each defined branches.
This speeds up the process considerably.
Closes #29616

maint: Make git scripts fetch origin once

---

src/lib/time/compat_time.c

There's an incorrect comment in compat_time.c that suggests we call
FreeLibrary() before we're done using the library's functions.
See 29642 for background.
Closes ticket 29643.

doc: Fix an incorrect comment about calling FreeLibrary() on Windows

---

scripts/maint/git-merge-forward.sh
scripts/maint/git-pull-all.sh

This appears at first glance to be a shellcheck bug.
Closes 29747.  Bugfix not in any released Tor.

Fix shellcheck warnings in pull-all/merge-all scripts

---

changes/bug27073
src/test/test_threads.c

Previously we just waited 200msec, which was not enough on slow/busy
systems.
Fixes bug 27073; bugfix on 0.2.6.3-alpha when the test was introduced.

In conditionvar_timeout test, wait for threads to timeout

---

changes/bug28096
src/common/compat.c

Correctly identify Windows 8.1, Windows 10, and Windows Server 2008
and later from their NT versions.
On recent Windows versions, the GetVersionEx() function may report
an earlier Windows version than the running OS. To avoid user
confusion, add "[or later]" to Tor's version string on affected
versions of Windows.
Remove Windows versions that were never supported by the
GetVersionEx() function.
Stop duplicating the latest Windows version in get_uname().
Fixes bug 28096; bugfix on 0.2.2.34; reported by Keifer Bly.

28096 029 squashed: Windows: fix uname on recent Windows versions

---

changes/bug25733
src/or/circuitstats.c

Prior to #23100, we were not counting HS circuit build times in our
calculation of the timeout. This could lead to a condition where our timeout
was set too low, based on non HS circuit build times, and then we would
abandon all HS circuits, storing no valid timeouts in the histogram.
This commit avoids the assert.

Bug 25733 029: Avoid assert failure if all circuits time out.

---

changes/bug23681
src/or/circuituse.c

A circuit with purpose C_INTRODUCING means that its state is opened but the
INTRODUCE1 cell hasn't been sent yet. We shouldn't consider that circuit when
looking for timing out "building circuit". We have to wait on the rendezvous
circuit to be opened before sending that cell so the intro circuit needs to be
kept alive for at least that period of time.
This patch makes that the purpose C_INTRODUCING is ignored in the
circuit_expire_building() which means that we let the circuit idle timeout
take care of it if we end up never using it.
Fixes #23681

circuit: Don't timeout opened C_INTRODUCING circuit

---

changes/bug29706_minimal
src/or/shared_random_state.c
src/or/shared_random_state.h
src/test/test_shared_random.c

Stop leaking parts of the shared random state in the shared-random unit
tests. The previous fix in 29599 was incomplete.
Fixes bug 29706; bugfix on 0.2.9.1-alpha.

test/sr: Free SRVs before replacing them in test_sr_setup_srv()

---

changes/bug28656
src/feature/nodelist/nodelist.c

Fixes bug 28656; bugfix on 0.3.5.1-alpha.

Stop logging a BUG() warning when tor is waiting for exit descriptors

---

scripts/maint/practracker/problem.py

Also, distinguish between empty lines (which we should ignore)
and incorrect lines (which we should warn about).

practracker: allow comments in exceptions file

---

scripts/maint/practracker/util.py

This helps ensure that we'll get output in a stable order.
Closes ticket 29882.

practracker: sort filenames and directories.

---

scripts/maint/practracker/practracker.py

Explicitly set the file encoding to UTF-8 in practracker.py, to avoid
problems in some CI environments.  Fixes bug 29789; bug not in any
released Tor.

bug29789 Set file encoding in practracker.py

---

changes/bug29823
src/test/test_shared_random.c

https://trac.torproject.org/projects/tor/ticket/29823

#29823: Refactor test_utils_general() to fix Coverity warnings

---

changes/bug28925
src/core/mainloop/connection.c
src/core/mainloop/connection.h
src/core/or/connection_or.c
src/core/or/or_connection_st.h

Previously, or_connection_t did not record whether or not the
connection uses a pluggable transport. Instead, it stored the
underlying proxy protocol of the pluggable transport in
proxy_type. This made bootstrap reporting treat pluggable transport
connections as plain proxy connections.
Store a separate bit indicating whether a pluggable transport is in
use, and decode this during bootstrap reporting.
Fixes bug 28925; bugfix on 0.4.0.1-alpha.

Correctly report PT vs proxy during bootstrap

---

changes/ticket29806
src/or/dirserv.c
src/test/test_dir.c

so that the relays that would be "excluded" from the bandwidth
file because of something failed can be included to diagnose what
failed, without still including these relays in the bandwidth
authorities vote.
Closes #29806.

bwauth: Ignore bandwidth file lines with "vote=0"

---

changes/bug29874
src/lib/process/process_win32.c

When NULL is given to lpApplicationName we enable Windows' "magical"
path interpretation logic, which makes Tor 0.4.x behave in the same way
as previous Tor versions did when it comes to executing binaries in
different system paths.
For more information about this have a look at the CreateProcessA()
documentation on MSDN -- especially the string interpretation example is
useful to understand this issue.
This bug was introduced in commit bfb94dd2ca8.
See: https://bugs.torproject.org/29874

#29874: Pass NULL to lpApplicationName in CreateProcessA().

---

changes/bug29939
src/test/test_routerkeys.c

After this fix, we have no more unchecked mkdir() calls.
Bug 29939; CID 144254. Bugfix on 0.2.7.2-alpha.

test_routerkeys.c: Always check mkdir() return value

---

src/lib/log/util_bug.c

In 9c132a5f9e87a2cd0f we replaced "buf" with a pointer and replaced
one instance of snprintf with asprintf -- but there was still one
snprintf left over, being crashy.
Fixes bug 29967; bug not in any released Tor. This is CID 1444262.

bug_occurred: a place where we assumed that "buf" was still a buffer

---

src/lib/pubsub/pubsub_check.c

This can't actually result in a null pointer dereference, since
pub_excl and sub_excl are only set when the corresponding smartlists
are nonempty.  But coverity isn't smart enough to figure that out,
and we shouldn't really be depending on it.
Bug 29938; CID 1444257.  Bug not in any released Tor.

Don't unconditionally deref pub and sub in lint_message_consistency

---

changes/ticket29913
scripts/maint/checkIncludes.py
scripts/maint/practracker/practracker.py
scripts/maint/rectify_include_paths.py
src/config/mmdb-convert.py
src/test/ope_ref.py

For scripts that work with python2, use /usr/bin/python.
Otherwise, use /usr/bin/env python3.
Fixes bug 29913; bugfix on 0.2.5.3-alpha.

Stop assuming that /usr/bin/python3 exists

---

changes/ticket29357
doc/tor.1.txt
src/app/config/config.c
src/app/config/or_options_st.h
src/core/mainloop/netstatus.c
src/test/test_mainloop.c

Closes ticket 29357, and comes with appropriate notions of caution.

Implement an DormantCanceledByStartup option

---

.travis.yml
changes/bug29036

See: https://bugs.torproject.org/29036

Run `make reset-gcov` after the script target in Travis CI is done.

---

changes/bug30021
src/common/tortls.c

When classifying a client's selection of TLS ciphers, if the client
ciphers are not yet available, do not cache the result. Previously,
we had cached the unavailability of the cipher list and never looked
again, which in turn led us to assume that the client only supported
the ancient V1 link protocol.  This, in turn, was causing Stem
integration tests to stall in some cases.  Fixes bug 30021; bugfix
on 0.2.4.8-alpha.

Do not cache bogus results from classifying client ciphers

---

.travis.yml
changes/bug30011

Diagnostic for 29437.
Fixes bug 30011; bugfix on 0.3.5.4-alpha.

Travis: Terminate test-stem if it takes more than 15 minutes to run

---

changes/bug28614_better_logging
src/feature/nodelist/networkstatus.c

When we fixed 28614, our answer was "if we failed to load the
consensus on windows and it had a CRLF, retry it."  But we logged
the failure at "warn", and we only logged the retry at "info".
Now we log the retry at "notice", with more useful information.
Fixes bug 30004.

Improve logging for 28614.

---

changes/bug29922
src/test/test_util.c

Fixes bug 29922; bugfix on 0.2.9.3-alpha when we tried to capture
all these warnings.  No need to backport any farther than 0.3.5,
though -- these warnings don't cause test failures before then.
This one was tricky to find because apparently it only happened on
_some_ windows builds.

Detect and suppress an additional gmtime() warning in test_util.c

---

src/test/test-network.sh

https://trac.torproject.org/projects/tor/ticket/29060

#29060: Stop requiring bash in test-network.sh. Make it POSIX compliant

---

changes/bug23790
src/or/rendservice.c

Turns out that when reloading a tor configured with hidden service(s), we
weren't copying all the needed information between the old service object to
the new one.
For instance, the desc_is_dirty timestamp wasn't which could lead to the
service uploading its descriptor much later than it would need to.
The replaycache wasn't also moved over and some intro point information as
well.
Fixes #23790

hs-v2: Copy needed information between service on prunning

---

changes/bug28698
src/core/or/circuituse.c

Signed-off-by: José M. Guisado <guigom@riseup.net>

Add circuit time check before logging about relaxing circuit time

---

changes/bug29144
src/core/mainloop/connection.c

When "auto" was used for the port number for a listening socket, the
message logged after opening the socket would incorrectly say port 0
instead of the actual port used.
Fixes bug 29144; bugfix on 0.3.5.1-alpha
Signed-off-by: Kris Katterjohn <katterjohn@gmail.com>

29144 035: Log the correct "auto" port number for listening sockets

---

changes/ticket27821
scripts/maint/practracker/exceptions.txt
src/core/or/connection_edge.c

Return an informative web page when the HTTPTunnelPort is used as an
HTTP proxy.
Closes ticket 27821, patch by "eighthave".

connection_edge: Return a web page when HTTPTunnelPort is misconfigured

---

changes/bug28269
src/feature/hs/hs_client.c
src/feature/hs/hs_common.c
src/feature/hs/hs_common.h
src/feature/rend/rendclient.c
src/test/test_hs.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/28269).

[Tor Trac #28269]: Make repeated/rate limited HSFETCH queries fail with QUERY_RATE_LIMITED

---

changes/bug29613
doc/tor.1.txt
scripts/maint/practracker/exceptions.txt
src/config/torrc.sample.in
src/core/or/policies.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/29613).

[Tor Trac #29613]: Make relays into exits when ExitRelay is auto and IPv6Exit is 1

---

src/test/test_hs_cache.c

Coverity doesn't like to see a path where we test a pointer for
NULL if we have already ready dereferenced the pointer on that
path.  While in this case, the check is not needed, it's best not to
remove checks from the unit tests IMO.  Instead, I'm adding an
earlier check, so that coverity, when analyzing this function, will
think that we have always checked the pointer before dereferencing
it.
Closes ticket 30180; CID 1444641.

Add an assertion to test_hs_cache.c to appease coverity.

---

changes/bug30001
src/feature/dircache/dircache.c
src/test/test_dir_handle_get.c

Previously we used time(NULL) to set the Expires: header in our HTTP
responses.  This made the actual contents of that header untestable,
since the unit tests have no good way to override time(), or to see
what time() was at the exact moment of the call to time() in
dircache.c.
This gave us a race in dir_handle_get/status_vote_next_bandwidth,
where the time() call in dircache.c got one value, and the call in
the tests got another value.
I'm applying our regular solution here: using approx_time() so that
the value stays the same between the code and the test.  Since
approx_time() is updated on every event callback, we shouldn't be
losing any accuracy here.
Fixes bug 30001. Bug introduced in fb4a40c32c4a7e5; not in any
released Tor.

30001: Fix a race condition in test_dir_handle_get.c

---

src/feature/dirauth/bwauth.c

We forgot to update function header comments and code comments when we
made changes in 0.3.5.1-alpha and later.
Closes 30112.

bwauth: update measured bandwidth file comments

---

Makefile.am
changes/bug30263

Fixes bug 30263; bugfix on 0.4.0.1-alpha.

Stop looking for scripts in the build directory during "make shellcheck"

---

changes/ticket30261
doc/HACKING/CodingStandards.md

Document how to find git commits and tags for bug fixes in
CodingStandards.md.
And update some changes file documentation.
Closes ticket 30261.

Coding Standards: Document how to find git commits

---

changes/bug30109
doc/tor.1.txt

Fixes bug 30109; bugfix on 0.1.0.1-rc.

doc: Improve the documentation for MapAddress .exit

---

changes/ticket27251
src/test/include.am

In "make test-network-all", test IPv6-only v3 single onion services,
using the chutney network single-onion-v23-ipv6-md. This test will
not pass until 23588 has been merged.
Closes ticket 27251.

test-network-all: Test IPv6-only v3 single onion services

---

src/core/or/sendme.c

The code flow in theory can end up with a layer_hint to be NULL but in
practice it should never happen because with an origin circuit, we must have
the layer_hint.
Just in case, BUG() on it if we ever end up in this situation and recover by
closing the circuit.
Fixes #30467.

sendme: Fix coverity CID 1444999

---

src/core/or/protover.c
src/core/or/protover.h
src/rust/protover/ffi.rs
src/rust/protover/protover.rs

See proposal 289 section 4.3 for more details.
It describes the flow control protocol at the circuit and stream level. If
there is no FlowCtrl protocol version, tor supports the unauthenticated flow
control features from its supported Relay protocols.
At this commit, relay will start advertising FlowCtrl=1 meaning they support
authenticated SENDMEs v1.
Closes #30363

sendme: Add FlowCtrl protover value

---

changes/bug30475
src/feature/hs/hs_service.c

Fortunately, in 0.3.5.1-alpha we improved logging for various
failure cases involved with onion service client auth.
Unfortunately, for this one, we freed the file right before logging
its name.
Fortunately, tor_free() sets its pointer to NULL, so we didn't have
a use-after-free bug.
Unfortunately, passing NULL to %s is not defined.
Fortunately, GCC 9.1.1 caught the issue!
Unfortunately, nobody has actually tried building Tor with GCC 9.1.1
before. Or if they had, they didn't report the warning.
Fixes bug 30475; bugfix on 0.3.5.1-alpha.

Don't pass a NULL into a %s when logging client auth file load failure

---

changes/bug30646
src/feature/control/control_cmd.c

This looks a copy-and-paste error to me.  Fixes bug 30646; bugfix on
0.4.1.1-alpha.

Remove want_cmddata from HSFETCH, which does not in fact want data

---

changes/bug30629
src/app/main/shutdown.c

This is necessary since shutting down libevent frees some pointer
that the subsystems want to free themselves. A longer term solution
will be to turn the evloop module into a subsystem itself, but for
now it is best to do the minimal fix.
Fixes bug 30629; bugfix on 0.4.1.1-alpha.

Shutdown libevent _after_ the subsystems.

---

changes/ticket30628
src/core/or/sendme.c

If "Log debug ..." is not set, the decrement never happens. This lead to the
package/deliver window to be out of sync at the stream level and thus breaking
the connection after 50+ cells.
Fixes #30628

sendme: Do not decrement window in a log_debug()

---

src/feature/hs/hs_descriptor.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/30774).

[Tor Trac #30774]: Add missing newline after decode_intro_points() closing bracket

---

.travis.yml
changes/bug30713
src/test/test_rebind.py
src/test/test_rebind.sh

Skip test_rebind when the TOR_SKIP_TEST_REBIND environmental variable
is set.
Skip test_rebind on macOS in Travis builds, because it is unreliable
on macOS on Travis.
Fixes bug 30713; bugfix on 0.3.5.1-alpha.

Travis: Skip test_rebind on macOS builds

---

.travis.yml
changes/bug30744

Allow the test-stem job to fail in Travis, because it sometimes hangs.
Fixes bug 30744; bugfix on 0.3.5.4-alpha.

Travis: allow the test-stem job to fail

---

changes/ticket29738
doc/tor.1.txt
src/app/config/config.c
src/app/config/or_options_st.h
src/feature/dirauth/dirvote.c
src/test/test_options.c

This is the first half of implementing proposal 301. The
RecommendedPackages torrc option is marked as obsolete and
the test cases for the option removed. Additionally, the code relating
to generating and formatting package lines in votes is removed.
These lines may still appear in votes from other directory authorities
running earlier versions of the code and so consensuses may still
contain package lines. A new consensus method will be needed to stop
including package lines in consensuses.
Fixes: #28465

Prop 301: No longer vote on RecommendedPackages

---

changes/bug30804
src/test/test_util.c

This can happen when we have no network stack configured. Fixes bug
30804; bugfix on 0.2.5.1-alpha.

Tolerate net-unreachable failures in util/socketpair_ersatz

---

changes/bug30956
doc/tor.1.txt
src/feature/relay/router.c

Always publish bridge pluggable transport information in the extra info
descriptor, even if ExtraInfoStatistics is 0. This information is
needed by BridgeDB.
Fixes bug 30956; bugfix on 0.4.1.1-alpha.

stats: Always publish pluggable transports in extra info documents

---

src/test/test_rebind.sh

Bugfix on be0a4be276c945e4e90b43ce8f784b5b75bef122 (not in any Tor release).
https://trac.torproject.org/projects/tor/ticket/30950

#30950: Fix shellcheck warning SC2034 in test_rebind.sh.

---

src/test/test_rebind.sh

Fixes a shellcheck issue; closes ticket 30964.  No user-visible
change.

Remove the unused "exitcode" variable from test_rebind.sh

---

changes/ticket31026
scripts/maint/practracker/exceptions.txt
src/core/or/connection_edge.c

Coverity doesn't understand that if begin_cell_parse() returns 0 and
sets is_begindir to 0, its address field will always be set.
Fixes bug 30126; bugfix on 0.2.4.7-alpha; Fixes CID 1447296.

begin_cell_parse(): Add an assertion to please coverity.

---

changes/ticket31025
src/ext/csiphash.c

Coverity has had trouble figuring out our csiphash implementation,
and has given spurious warnings about its behavior.
This patch changes the csiphash implementation when coverity is in
use, so that coverity can figure out that we are not about to read
beyond the provided input.
Closes ticket 31025.

Coverity: different implementation for csiphash

---

changes/bug31040
scripts/git/post-merge.git-hook

https://trac.torproject.org/projects/tor/ticket/31040

#31040: Early exit from post-merge git hook script when not merging to master

---

changes/bug31003
src/feature/nodelist/routerlist.c

There is other code that uses this value, and some of it is
apparently reachable from inside router_dir_info_changed(), which
routerlist_free() apparently calls.  (ouch!)  This is a minimal fix
to try to resolve the issue without causing other problems.
Fixes bug 31003. I'm calling this a bugfix on 0.1.2.2-alpha, where
the call to router_dir_info_changed() was added to routerlist_free().

Set 'routerlist' global to NULL before freeing it.

---

changes/bug30942
src/core/or/relay.c

Padding circuits were regular cells that got closed before their padding
machine could finish. This means that they can still receive regular cells from
their past life, but they have no way or reason to answer them anymore. Hence
let's ignore them before they even get to the proper subsystems.

Ignore regular cells in padding circuits.

---

Makefile.am
changes/ticket31309

We have Makefile.am use this to decide how to invoke practracker on
the Tor source.

practracker: add envvar TOR_PRACTRACKER_OPTIONS

---

Makefile.am
changes/ticket31311

Previously, we included temporary files and whatnot, which is not
good.
Fixes bug 31311; bugfix on 0.4.1.1-alpha.

make dist: only include files from practracker dir intentionally.

---

changes/ticket31012
doc/tor-print-ed-signing-cert.1.txt
src/tools/tor-print-ed-signing-cert.c

https://trac.torproject.org/projects/tor/ticket/31012

#31012: Make tor-print-ed-signing-cert output RFC1123 and unix timestamps as well

---

src/core/or/relay.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/31207).

[Tor Trac #31207]: Space out first connection_edge_process_relay_cell() line in circuit_receive_relay_cell()

---

changes/bug31343
src/or/channeltls.c
src/or/routerlist.c

On some windows builds, time_t is 64 bits but long is not.  This is
causing appveyor builds to fail.
Also, one of our uses of labs() on time_t was logically incorrect:
it was telling us to accept NETINFO cells up to three minutes
_before_ the message they were responding to, which doesn't make
sense.
This patch adds a time_abs() function that we should eventually move
to intmath.h or something.  For now, though, it will make merges
easier to have it file-local in channeltls.c.
Fixes bug 31343; bugfix on 0.2.4.4-alpha.

Avoid using labs() on time_t in channeltls.c

---

changes/ticket31374
src/common/compat_time.c

Fixes bug 31374; bugfix on 0.2.9.1-alpha.

Fix a warning about casting the results of GetProcAddress.

---

changes/bug28525
src/common/address.c
src/test/test_addr.c

28525 029: Make tor_addr_is_internal_() RFC6598 (Carrier Grade NAT) aware

---

doc/tor.1.txt
src/config/torrc.sample.in

We changed the default of ExitRelay in #21530 in 0.3.5.1-alpha, but
forgot to update the documentation.
Closes 29612.

29612 035: doc: update the man page and sample torrc for ExitRelay

---

changes/bug30190
src/lib/crypt_ops/crypto_openssl_mgt.c

Do not warn about compatible OpenSSL upgrades.
When releasing OpenSSL patch-level maintenance updates,
we do not want to rebuild binaries using it.
And since they guarantee ABI stability, we do not have to.
Without this patch, warning messages were produced
that confused users:
https://bugzilla.opensuse.org/show_bug.cgi?id=1129411

Do not warn about compatible OpenSSL upgrades

---

changes/bug30189
src/lib/log/util_bug.c
src/lib/log/util_bug.h

Previously, our use of abort() would break anywhere that we didn't
include stdlib.h.  This was especially troublesome in case where
tor_assert_nonfatal() was used with ALL_BUGS_ARE_FATAL, since that
one seldom gets tested.
As an alternative, we could have just made this header include
stdlib.h.  But that seems bloaty.
Fixes bug 30189; bugfix on 0.3.4.1-alpha.

Use a tor_abort_() wrapper in our util_bug.h macros

---

changes/bug30316
src/feature/dirauth/dirvote.c

Fixes bug 30316; bugfix on 0.3.5.1-alpha.

Move bandwidth-file-headers line to appear in the correct vote section

---

changes/ticket29617
src/feature/relay/dns.c

Previously we purged it in 1-hour increments -- but one-hour is the
maximum TTL for the cache!  Now we do it in 25%-TTL increments.
Fixes bug 29617; bugfix on 0.3.5.1-alpha.

OOM-purge the DNS cache one part at a time

---

changes/bug29670
src/core/mainloop/connection.c

Previously, we were looking at our global settings to see what kind
of proxy we had.  But doing this would sometimes give us the wrong
results when we had ClientTransportPlugin configured but we weren't
using it for a particular connection.  In several places in the
code, we had added checks to see if we were _really_ using a PT or
whether we were using a socks proxy, but we had forgotten to do so
in at least once case.  Instead, since every time we call this
function we are asking about a single connection, it is probably
best just to make this function connection-specific.
Fixes bug 29670; bugfix on 0.2.6.2-alpha.

Make get_proxy_type() connection-specific

---

changes/bug29034
src/core/or/circuituse.c

Leave the other rend and hs_ident data around until circuit free, since code
may still try to inspect it after marking the circuit for close. The
circuitmap is the important thing to clean up, since repurposed
intropoints must be removed from this map to ensure validity.

Bug 29034: Cleanup hs circuitmap when purpose changes.

---

src/test/test_util.c

Fixes bug 31352; bug not in any released Tor.

test_util: Do not check for ENETUNREACH unless it exists.

---

src/test/test_token_bucket.c

Previously we tried multiplying by -1 before casting to int32_t,
which would cause us to cast the -1 to an unsigned before we
multiplied.  This gave us compiler warnings on windows.
Fixes bug 31353; bug not in any released Tor.

test_token_bucket: negate after casting to signed type.

---

scripts/maint/practracker/exceptions.txt
src/core/or/relay.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/31366).

Move the connection_edge_process_relay_cell() assignments out of if statements in circuit_receive_relay_cell()

---

changes/ticket29879
scripts/git/git-push-all.sh

Add a TOR_PUSH_DELAY variable to git-push-all.sh, which makes the script
push master and maint branches with a delay between each branch. These
delays trigger the CI jobs in a set order, which should show the most
likely failures first.
Also:
* make pushes atomic by default, and
* make the script pass any command-line arguments to git push.
Closes ticket 29879.

scripts/git: add TOR_PUSH_DELAY to git-push-all.sh

---

doc/HACKING/CodeStructure.md
doc/HACKING/EndOfLifeTor.md
doc/HACKING/Fuzzing.md
doc/HACKING/ReleasingTor.md

This PR enable to display the code structure as list in the markdown generation.
Which enhances readability of the file `CodeStructure.md`.
This PR also changes some titles using `=` by `#` as the former seems to not be understood by the markdown parser.
If both changes suit you, I can squash the two commits.

Fix #31478: Update CodeStructure.md compliance to markdown 

---

changes/bug31462
changes/ticket30979
scripts/git/pre-commit.git-hook
scripts/git/pre-push.git-hook

The pre-push hook already calls the pre-commit hook, which calls
practracker.
Also update the script comments to avoid similar issues in future.
Fixes bug 31462; bugfix on 0.4.1.1-alpha.

scripts/git: Remove a duplicate practracker call from the pre-push hook

---

scripts/git/git-push-all.sh

(I've chosen to suppress some instances rather than 'fix' them,
since the fix would require arrays or major refactoring.)
Fixes bug 31519; bug not in any released Tor.

Fix/suppress shellcheck warnings in git-push-all.sh

---

src/test/test_circuitbuild.c

Coverity wants us to free everything that we are potentially
allocating, even stuff where allocating it would be a bug.  Adding
a smartlist_free() here will fix the warning.
Fixes bug 31452; bugfix on 16a0b7ed6779bf72a8a471c, which is not in
any released Tor.  This is CID 1447292.

Fix a memory-leak warning in test_circuitbuid.c

---

changes/ticket31451
src/lib/log/log.c

If unsigned int is 32-bits long, then our old code would give a
wrong result with any log domain whose mask was >= (1<<32).
Fortunately, there are no such log domains right now: the domain
mask is only 64 bits long to accommodate some flags.
Found by coverity as CID 1452041.
Fixes bug 31451; bugfix on 0.4.1.4-rc.

Fix 64-bit return issue in parse_log_domain()

---

changes/bug31490
src/core/or/circuituse.c
src/feature/hs/hs_circuit.c
src/feature/hs/hs_ident.c
src/feature/hs/hs_ident.h
src/test/test_hs_client.c
src/test/test_hs_service.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/31490).

[Tor Trac #31490]: Remove the unused circuit_type field from hs_ident_circuit_t and hs_ident_circuit_new()

---

.travis.yml
changes/bug31463

The main build doesn't use HARDENING_OPTIONS, so the exclude shouldn't,
either. Reduces the number of builders by one.

Fix gcc build exclude on travis

---

.travis.yml
changes/bug31442
configure.ac

The #[global_allocator] attribute is not available in previous versions

Rust: require at least rustc version 1.28

---

changes/bug30894
src/app/config/confparse.c

Fixes bug 30894; bugfix on 0.3.4.1-alpha

Fix memleak when failing to parse a CSV_INTERVAL.

---

changes/ticket30871
src/feature/client/entrynodes.c
src/test/test_circuitbuild.c

When we consider all circuits in "waiting for guard" state to be promoted to
an "open" state, we were considering all circuits, even the one marked for
close.
This ultiamtely triggers a "circuit_has_opened()" called on the circuit that
is marked for close which then leads to possible undesirable behaviors within
a subsystem.
For instance, the HS subsystem would be unable to find the authentication key
of the introduction point circuit leading to a BUG() warning and a duplicate
mark for close on the circuit.
This commit also adds a unit test to make sure we never select marked for
close circuits when upgrading its guard state from waiting for guard to open.
Fixes #30871

guard: Ignore marked for close circuit when changing state to open

---

src/feature/rend/rendcommon.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/31579)

[Tor Trac #31579]:  Space out the arguments to the cell functions in rend_process_relay_cell()

---

Makefile.am
scripts/maint/practracker/README
scripts/maint/practracker/includes.py
scripts/maint/practracker/practracker.py

Document new practracker violation types, and add a practracker readme

---

changes/ticket31529
src/app/config/confparse.c

When we parse a CLEAR line (e.g., "/OrPort" or /OrPort blah blah"),
we always suppress the value, even if one exists.  That means that
the block of code was meant to handle CLEAR lines didn't actually do
anything, since we previously handled them the same way as with
other empty values.
Closes ticket 31529.

config: Make CLEAR with a nonempty value into a nonfatal assertion.

---

src/lib/conf/conftypes.h

Also add an explanation of a possible future refactoring where we
might remove the config_type_t enumeration entierly.
Fixes ticket 31624.
No changes file, since this is a comment-only change.

config: explain CONFIG_TYPE_EXTENDED

---

src/lib/confmgt/structvar.c
src/lib/confmgt/structvar.h

These turned out to be unnecessary, so let's not keep them around
and let them start getting complicated.
Closes ticket 31630.

Remove unused struct_var_* functions.

---

changes/ticket31673
src/lib/meminfo/meminfo.c

build: The <sys/sysctl.h> is now deprecated on Linux

---

changes/ticket31475
src/lib/confmgt/type_defs.c
src/test/test_confparse.c

This lets us detect erroneous doubles, which previously we could not
do.
Fixes bug 31475; bugfix on commit 00a9e3732e88, a.k.a svn:r136.

Use strtod, not atof, for parsing doubles in the configuration.

---

changes/bug31696
src/lib/malloc/map_anon.c

These errors can occur if we are built on a system with support for
madvise(MADV_NOFORK) but then we are run on a system whose kernel
does not support that flag.
If the error is something that we don't tolerate at all, we now log
it before crashing.
Fixes bug 31696.  I am calling this a bugfix on 0.4.1.1-alpha, where
we actually started using the map_anon code.
This is similar to, but not the same as, the fix for #31570.

madvise: tolerate EINVAL and ENOSYS when minherit fails

---

changes/bug31552
src/feature/dirauth/keypin.h
src/feature/dirauth/process_descs.h
src/feature/dirauth/reachability.h

This fixes LTO compilation for Android and -O0 compilation in
general, when --disable-module-dirauth is provided.
Fixes bug 31552; bugfix on 0.4.1.1-alpha.

Stub out some more functions in dirvote/*.h, fix compilation.

---

changes/bug31570
src/lib/malloc/map_anon.c

These errors can occur if we are built on a system with support for
madvise(MADV_NOFORK) but then we are run on a system whose kernel
does not support that flag.
If the error is something that we don't tolerate at all, we now log
it before crashing.
Fixes bug 31570.  I am calling this a bugfix on 0.4.1.1-alpha, where
we actually started using the map_anon code.

madvise: tolerate EINVAL and ENOSYS

---

changes/ticket31772
src/feature/control/control_cmd.c

In 0.4.1.1-alpha I introduced a bug where we would require and
ignore a single positional argument.
Fixes bug 31772.

Correct the syntax description for the MAPADDRESS command.

---

changes/ticket30743
scripts/coccinelle/debugmm.cocci

Add a coccinelle script to look for {inc,dec}rements in log_debug

---

changes/bug31825
configure.ac

Explain what the optional Directory Authority module is, and what
happens when it is disabled.
Fixes bug 31825; bugfix on 0.3.4.1-alpha.

configure: Explain --disable-module-dirauth better

---

changes/ticket31589
scripts/maint/practracker/exceptions.txt
src/feature/hs/hs_descriptor.c
src/feature/hs/hs_descriptor.h
src/test/fuzz/fuzz_hsdescv3.c

[Ticket](https://trac.torproject.org/projects/tor/ticket/31589)
```
============================================================================
Testsuite summary for tor 0.4.2.0-alpha-dev
============================================================================
============================================================================
make[2]: Leaving directory '/hdd/programming/cpp/tor'
perl ./scripts/maint/checkSpace.pl -C \
./src/lib/*/*.[ch] ./src/core/*/*.[ch] ./src/feature/*/*.[ch] ./src/app/*/*.[ch] ./src/test/*.[ch] ./src/test/*/*.[ch] ./src/tools/*.[ch]
python3 ./scripts/maint/practracker/includes.py
(warning) problem file-size /src/app/config/or_options_st.h 1121
(warning) problem function-size /src/feature/dirparse/microdesc_parse.c:microdescs_parse_from_string() 171 …
```

Ticket31589 042 01

---

changes/bug31334
src/lib/log/log.c
src/lib/log/log.h
src/test/fuzz/fuzzing_common.c
src/test/test_logging.c
src/test/test_options.c
src/test/testing_common.c

Move SEVERITY_MASK_IDX() to log.h private/unit tests section, so that
we can use it in log.c and the unit tests.
Fixes bug 31334; bugfix on 0.2.5.2-alpha.

test/logging: Use SEVERITY_MASK_IDX() to find the LOG_ERR mask index

---

src/feature/nodelist/routerset.c
src/lib/confmgt/type_defs.c
src/lib/confmgt/var_type_def_st.h

There is a bad design choice in two of our configuration types,
where the empty string encodes a value that is not the same as the
default value.  This design choice, plus an implementation mistake,
meant that config_dup() did not preserve the value of routerset_t,
and thereby caused bug #31495.
This comment-only patch documents the two types with the problem,
and suggests that implementors try to avoid it in the future.
Closes ticket 31907.

Add comments to try to prevent recurrence of #31495.

---

src/test/test_util.c

This fixes coverity CID 1454593, and bug 31948. Bug not in any
released version of Tor.

util/map_anon_nofork: Add a cast to avoid passing -48 to memset

---

changes/ticket29669
src/feature/control/control_cmd.c
src/test/test_controller.c

From RSA1024 (v2) to v3 now.
Closes #29669

hs: ADD_ONION NEW:BEST now defaults to ED25519-V3

---

changes/bug30344
src/core/mainloop/connection.c
src/core/mainloop/mainloop.c

Code adapted from Rob's proposed patch in #30344.
Also add a comment in connection_mark_for_close_internal_() on why we should
not be adding extra code there without a very good reason.

Stop libevent from reading data from closed connections.

---

changes/ticket32063
src/feature/hs/hs_cell.c

Found by coverity CID 1454769.
There were a second possible leak that is also fixed in this commit.
Fixes #32063

hs-v3: Fix possible memory leak in error code path

---

changes/bug31810
scripts/maint/practracker/exceptions.txt
src/lib/process/process_unix.c
src/lib/process/process_win32.c
src/test/test_process_slow.c

Same as #1424, but for 0.4.2. This includes an additional patch for added practracker happiness.

[0.4.2] #31810 execve() error handling

---

.appveyor.yml
changes/ticket32086

Instead of Windows Server 2016.
Closes ticket 32086.

Appveyor: Use Windows Server 2019

---

.travis.yml
changes/ticket32177

We need to mitigate slow scheduling of Travis macOS jobs.
Closes ticket 32177.

Travis: Disable all but one macOS build

---

changes/31147
src/feature/control/control_events.c
src/lib/buf/buffers.c
src/lib/process/process.c

Add extra sanity checks around tor_vasprintf().

#31147: Sanity checks for tor_vasprintf().

---

.travis.yml
changes/ticket31372_travis

Frequently, when a patch fails, it has failures in several files.
Using the "-k" flag will let us learn all the compilation errors,
not just the first one that the compiler hits.
Based on a patch by rl1987.

Try using make -k in Travis configuration

---

.appveyor.yml
changes/ticket31372_appveyor

Frequently, when a patch fails, it has failures in several files.
Using the "-k" flag will let us learn all the compilation errors,
not just the first one that the compiler hits.
Based on a patch by rl1987.
Closes ticket 31372.

Try using make -k in the Appveyor configuration

---

src/test/test_options.c

This prevents a warning when building for 32-bit targets.
Fixes bug 32269; bug not in any released Tor.

test_options: Use 64-bit comparisons when checking domain masks.

---

changes/ticket32094
src/feature/hs/hs_circuit.c
src/feature/hs/hs_circuit.h
src/feature/hs/hs_service.c
src/feature/hs/hs_service.h
src/test/test_hs_service.c

Only use the HS circuit map to know if an introduction circuit is established
or not. No need for a flag to keep state of something we already have in the
circuit map. Furthermore, the circuit map gets cleaned up properly so it will
always have the "latest truth".
This commit also removes a unit test that was testing specifically that flag
but now we rely solely on the HS circuit map which is also tested few lines
below the removed test.
Fixes #32094

hs-v3: Remove the circuit_established intro flag

---

changes/bug25568
src/feature/rend/rendcache.c
src/feature/rend/rendcache.h
src/feature/rend/rendclient.c

When picking an intro point from the service descriptor, the client failed to
lookup the failure cache.
It made an HS v2 client re-pick bad intro points for which we already know it
won't work in the first place.
Based on Neel Chauhan original patch.
Fixes #25568

hs-v2: Lookup intro failure cache when picking an intro from descriptor

---

Doxyfile.in
configure.ac

Our @top_srcdir@ directory can contain "..", which confuses doxygen
when it tries to make references to directories.  Using
@abs_top_srcdir@ has the same problem.  Instead, we should use our
@SRCDIR@ configuration variable, which is canonicalized.

doxygen: Use @SRCDIR@ instead of @top_srcdir@.

---

Doxyfile.in
Makefile.am

This time, we're using cd to run doxygen from inside the source
directory, not the build directory at all.  This lets us call the
source directory ".", which (I hope) both Doxygen 1.8.13 and 1.8.15
will understand.
Naturally, this requires a corresponding change in the doxygen
configuration so that we are directing the output to the correct
place.
Fix for 32378.

Another attempt to fix Doxygen references in out-of-tree builds

---

changes/ticket31466
src/or/connection_edge.c

This warning would previously be given every time we tried to open a
connection to a foo.exit address, which could potentially be used to
flood the logs.  Now, we don't allow this warning to appear more
than once every 15 minutes.
Fixes bug 31466; bugfix on 0.2.2.1-alpha, when .exit was first
deprecated.

Add a rate-limit to our warning about the disabled .exit notation

---

changes/bug31107
src/or/channeltls.c

We previously used tor_fragile_assert() to declare that this case
could not happen: VERSIONS cells are always supposed to be
variable-sized, right?
This is incorrect, though.  On a v1 link protocol connection, all
cells are fixed-sized.  There aren't supposed to be any VERSIONS
cells with this version of the protocol, but apparently, somebody
was messing up.  (The v1 link protocol is obsolete, so probably the
implementer responsible didn't mean to be using it.)
Fixes bug 31107.  Bugfix on 0.2.4.4-alpha, when we introduced a
tor_fragile_assert() for this case.

Treat an unexpected constant-sized VERSIONS cell as a PROTOCOL_WARN.

---

changes/bug31837
src/test/test_rebind.py

* actually sleep when tor has not logged anything
* log at debug level when waiting for tor to log something
* backslash-replace bad UTF-8 characters in logs
* format control messages as ASCII: tor does not accept UTF-8 control commands
Fixes bug 31837; bugfix on 0.3.5.1-alpha.

test/rebind: Make control formatting and log parsing more robust

---

changes/bug31408
src/lib/fs/conffile.c
src/test/test_config.c

When processing a %included folder, a bug caused the pointer to
the last element of the options list to be set to NULL when
processing a file with only comments or whitepace. This could
cause options from other files on the same folder to be
discarded depending on the lines after the affected %include.

Fix bug when %including folder with comment only files. #31408

---

changes/bug31897
src/test/test_util.c

This test failure happened due to a signed/unsigned integer
comparison.
This bug occurred on SunOS, it may also occur on other systems that
use signed char as the default. (And cast 1-byte integer constants
to an unsigned integer.)
Fixes bug 31897; bugfix on 0.4.1.1-alpha.

test: Avoid a map_anon_nofork test failure on SunOS

---

configure.ac

The "if-present" clause of AC_ARG_ENABLE() sets enable_{lzma,zstd},
so we don't need to set it. The "if-not-present" clause needs to set
enable_{lzma,zstd}, rather than just {lzma,zstd}.
The rest of the script only ever checks for enable_{lzma,zstd} = no,
so these changes do not actually change the behaviour of configure.
Fixes bug 32401.

configure: Fix variable name typos

---

Makefile.am
changes/bug31335

Previously, it would run on the build tree, which did not contain
any sources.
Fixes bug 31335; bugfix on 0.3.5.1-alpha.

Makefile: Fix "make check-includes" for out-of-tree builds

---

changes/ticket32410
src/app/config/config.c
src/app/config/or_options_st.h
src/feature/relay/relay_config.h
src/test/conf_examples/badnick_1/error_no_dirauth_relay
src/test/conf_examples/badnick_1/expected_no_dirauth_relay
src/test/conf_examples/badnick_1/torrc
src/test/conf_examples/badnick_2/error_no_dirauth_relay
src/test/conf_examples/badnick_2/expected_no_dirauth_relay
src/test/conf_examples/badnick_2/torrc
src/test/conf_examples/contactinfo_notutf8/error_no_dirauth_relay
src/test/conf_examples/contactinfo_notutf8/expected_no_dirauth_relay
src/test/conf_examples/contactinfo_notutf8/torrc
src/test/conf_examples/example_1/error_no_dirauth_relay
src/test/conf_examples/example_3/error_no_dirauth_relay
src/test/conf_examples/pt_01/error_no_dirauth_relay
src/test/conf_examples/pt_02/error_no_dirauth_relay
src/test/conf_examples/pt_02/expected_no_dirauth_relay
src/test/conf_examples/pt_02/torrc
src/test/conf_examples/pt_03/error_no_dirauth_relay
src/test/conf_examples/pt_04/error_no_dirauth_relay
src/test/conf_examples/pt_06/error_no_dirauth_relay
src/test/conf_examples/pt_08/error_no_dirauth_relay
src/test/conf_examples/pt_08/expected_no_dirauth_relay
src/test/conf_examples/pt_08/torrc
src/test/conf_examples/relay_01/error_no_dirauth_relay

When the relay module is disabled, make "DirCache 0" the default.
(But keep "DirCache 1" as the default for the unit tests.)
Closes ticket 32410.

relay: Stop failing on startup when the relay module is disabled

---

.appveyor.yml
changes/bug32449

Install the mingw OpenSSL package in Appveyor. This makes sure that
the OpenSSL headers and libraries match in Tor's Appveyor builds.
(This bug was triggered by an Appveyor image update.)
Fixes bug 32449; bugfix on 0.3.5.6-rc.

Appveyor: Install OpenSSL to resolve a header/library mismatch

---

src/test/conf_examples/empty_3/torrc
src/test/conf_examples/empty_4/error
src/test/test_parseconf.sh

And document the "%include" behaviour.
Closes 32450.

test/parseconf: Add basic parsing tests

---

changes/ticket32163
src/feature/dirauth/reachability.h
src/feature/nodelist/routerlist.c

There are now no HAVE_MODULE_{DIRAUTH,RELAY} inside functions.
Closes ticket 32163.

dirauth: Remove a HAVE_MODULE_DIRAUTH inside a function

---

src/feature/dircommon/consdiff.c

For the ticket [here](https://trac.torproject.org/projects/tor/ticket/32513).

[Tor Trac #32513]: Remove the extra whitespace in the lines_eq() if statement in consdiff_gen_diff() 

---

src/app/config/config.c
src/test/test_options.c

For the bug [here](https://trac.torproject.org/projects/tor/ticket/32514).

[Tor Trac #32514]: Remove the extra whitespace around the DARWIN #defines

---

src/app/config/config.c

Also free options objects when we discard them due to
TestingTorOptions.
Fixes bug 32555; bug not in any released Tor.

Free options objects for which validation fails.

---

src/lib/conf/config.md
src/mainpage.md

High-level documentation of configuration in Tor.

---

src/app/config/config.c

Found by Coverity as CID 1455953
Fixes bug 32575; bug not in any released Tor.

Fix a low-impact memory leak in options_act_reversible()

---

changes/ticket28970
src/feature/hs/hs_client.c

hs_client_purge_state() and hs_cache_clean_as_client() can remove a descriptor
from the client cache with a NEWNYM or simply when the descriptor expires.
Which means that for an INTRO circuit being established during that time, once
it opens, we lookup the descriptor to get the IP object but hey surprised, no
more descriptor.
The approach here is minimalist that is accept the race and close the circuit
since we can not continue. Before that, the circuit would stay opened and the
client wait the SockTimeout.
Fixers #28970.

hs-v3: Remove a BUG() caused by an acceptable race

---

changes/ticket32058
src/core/mainloop/periodic.c

When tearing down all periodic events during shutdown, disable them first so
their enable flag is updated.
This allows the tor_api.h to relaunch tor properly after a clean shutdown.
Fixes #32058

mainloop: Disable periodic events before a destroy

---

changes/ticket31548
src/feature/hs/hs_service.c

When encoding introduction points, we were not checking if that intro points
had an established circuit.
When botting up, the service will pick, by default, 3 + 2 intro points and the
first 3 that establish, we use them and upload the descriptor.
However, the intro point is removed from the service descriptor list only when
the circuit has opened and we see that we have already enough intro points, it
is then removed.
But it is possible that the service establishes 3 intro points successfully
before the other(s) have even opened yet.
This lead to the service encoding extra intro points in the descriptor even
though the circuit is not opened or might never establish (#31561).
Fixes #31548

hs-v3: Make service pick the exact amount of intro points

---

changes/bug31939
src/lib/tls/buffers_tls.c

Rather than filling the logs with similar warnings.
Fixes bug 31939; bugfix on 0.3.0.4-rc.

tls: Log TLS read buffer length bugs once

---

changes/bug32108
src/core/mainloop/mainloop.c

Relays now respect their AccountingMax bandwidth again. When relays
entered "soft" hibernation (which typically starts when we've hit
90% of our AccountingMax), we had stopped checking whether we should
enter hard hibernation. Soft hibernation refuses new connections and
new circuits, but the existing circuits can continue, meaning that
relays could have exceeded their configured AccountingMax.
This commit rolls back some of the cpu-saving fixes, where we tried
to avoid calling so many of our events while we're off the network.
That's because PERIODIC_EVENT_FLAG_NEED_NET checks net_is_disabled(),
which returns true even if we're only in soft hibernation.
Fixes bug 32108; bugfix on 0.4.0.1-alpha.

#32108: respect accountingmax during soft hibernation [0.4.0]

---

changes/ticket31091
src/feature/client/transports.c

This patch removes an overly strict tor_assert() and an ignorable BUG()
expression. Both of these would trigger if a PT was unable to configure
itself during startup. The easy way to trigger this is to configure an
obfs4 bridge where you make the obfs4 process try to bind on a port
number under 1024.
See: https://bugs.torproject.org/31091

[0.4.0] Remove overly strict assertions in transports.c.

---

changes/ticket32608
configure.ac

Python 2 will be end-of-life as of 1 Jan 2020, so we can finally
stop supporting it.  As a first step, we should make our configure
script stop accepting python 2 as something acceptable to run our
tests with.
Closes ticket 32608.

configure: reject Python 2.

---

src/lib/process/setuid.c

For the ticket [here](https://trac.torproject.org/projects/tor/ticket/32625).

[Tor Trac #32625]: If statements to getresuid() and getresgid() in setuid.c shouldn't have an extra space

---

src/feature/hs/hs_circuit.c

Found by Stem regression tests. Reported by atagar.
Fixes #32664

hs-v3: Fix NULL deref. in hs_circ_service_get_established_intro_circ()

---

changes/bug31810
src/lib/process/process_unix.c
src/lib/process/process_win32.c
src/test/test_process_slow.c

These patches makes execve() error handling slightly better on Unix and adds a test case that made us notice that we did not run the exit callback when CreateProcessA() fails on Windows.

[0.4.0] #31810 execve() error handling

---

changes/ticket32206
src/arch_goals.md
src/mainpage.md

Create a high-level description of the long-term software architecture
goals.  Closes ticket 32206.

ticket32206 Document high-level architecture goals

---

changes/bug32639
src/feature/hs/hs_client.c

Ticket: https://trac.torproject.org/projects/tor/ticket/32639

In cancel_descriptor_fetches(), use connection_list_by_type_purpose() instead of cancel_descriptor_fetches()

---

scripts/coccinelle/check_cocci_parse.sh

No changes file required: not in any released version of tor.
Fixes bug 32663.

cocci: Require spatch >= 1.0.4 to run checks

---

.travis.yml
changes/ticket32242

Recent Ubuntu versions have zstd >= 1.1, which is an optional tor build
dependency.
Closes ticket 32242.

Travis: Use zstd in our Travis Linux builds

---

changes/bug29819
src/lib/sandbox/sandbox.c

This fixes a startup crash with libseccomp v2.4.0 if Sandbox is
set to 1.

Correct how we use libseccomp

---

changes/ticket32807
doc/tor.1.txt
src/app/config/config.c
src/app/config/or_options_st.h
src/app/config/testnet.inc
src/test/test_options.c

We stopped looking at this option in 85cf6dcba3693b, back when we
implemented the minimal pieces of prop275.  Since then, we've had
code to validate and adjust this option, and to give it a different
value in testing networks, but the option hasn't actually done
anything.
We can safely mark it as OBSOLETE, since doing so does not make any
old configuration get rejected.
Closes ticket 32807.

Mark TestingEstimatedDescriptorPropagationTime as obsolete.

---

changes/ticket32705_disable
scripts/maint/practracker/test_practracker.sh

When practracker is disabled, its output will be empty.  We don't
want that happening during our tests.
Fixes bug 32705; bugfix on 0.4.2.1-alpha, when test_practracker.sh
was introduced.

test_practracker.sh: never disable practracker

---

src/feature/rend/rendcache.c

When looking up an entry in the rend_cache, stop asserting that it exists but
rather confirm it exists and if not, return that no entry was found.
The reason for that is because the hs_circ_cleanup_on_free() function (which
can end up looking at the rend_cache) can be called from the
circuit_free_all() function that is called _after_ the rend cache is cleaned
up in tor_free_all().
We could fix the free all ordering but then it will just hide a future bug.
Instead, handle a missing rend_cache as a valid use case as in while we are in
the cleanup process.
As Tor becomes more modular, it is getting more and more difficult to ensure
subsystem callstack ordering thus this fix aims at making the HSv2 subsystem
more robust at being called while tor is pretty much in any kind of state.
Fixes …

hs-v2: Always check rend_cache validity before using it

---

changes/bug32942
doc/tor.1.txt
src/app/config/config.c

Ticket: https://trac.torproject.org/projects/tor/ticket/32942

[Tor Trac #32942]: Deprecate the ClientAutoIPv6ORPort option

---

changes/bug32884
src/lib/thread/compat_pthreads.c

Fixes bug 32884.  This is a bugfix on 0.3.3.1-alpha, when we started
allowing restart-in-process with tor_api.h.

When initializing pthreads, always set the main thread.

---

changes/ticket32407
src/core/mainloop/mainloop.c
src/lib/evloop/compat_libevent.c
src/lib/evloop/compat_libevent.h

Doing so caused us to crash in some unusual circumstances, such as
using --verify-config to verify a configuration that failed during
the options_act() stage.
Fixes bug 32407; bugfix on 0.3.3.1-alpha.

Do not try to shut down the event loop when it is not initialized.

---

changes/bug32753
src/feature/relay/relay_config.c
src/feature/relay/router.c
src/test/test_config.c

This PR contains patches that adds test for the BridgeDistribution option validator and makes sure we lowercase the value before adding it to the descriptor.

#32753: Lowercase BridgeDistribution from torrc

---

scripts/git/pre-commit.git-hook
scripts/git/pre-push.git-hook

We no longer will be pushing or committing things in branches that
use src/common or src/or.
Resolves ticket 32957.

Git hooks: remove support for 0.2.9 directory layout.

---

changes/bug32778
src/app/main/main.c
src/app/main/main.h
src/app/main/ntmain.c

Fixes bug 32778; bugfix on 0.4.1.1-alpha.

Initialize publish/subscribe code when running as an NT service.

---

changes/ticket32706
src/feature/rend/rendmid.c

All of those can be triggered remotely so change them to protocol warnings.
Fixes #32706

hs-v2: Turn logs into protocol warning

---

changes/ticket33139
src/feature/hs/hs_client.c
src/feature/hs/hs_client.h
src/test/test_hs_client.c

hs-v3: Purge ephemeral client auth on NEWNYM

---

scripts/codegen/makedesc.py

Fixes: https://trac.torproject.org/projects/tor/ticket/32791#comment:3
Unblocks: #1686
`flake8 --select=F401` will also find seven other unused imports.

Remove unused import UserDict

---

changes/ticket33103
src/feature/control/control_getinfo.c

Fixes bug 33103; bugfix on 0.4.3.1-alpha.

Fix a memory leak in handling GETINFO.

---

doc/tor.1.txt

- Created new sections for Timeout and Node Options as discussed in https://trac.torproject.org/projects/tor/ticket/32846#comment:11.
- Moved 7 options from the Client Options section to the new **Timeout Options** section.
- Moved 9 options from the Client Options section to the new **Advanced Options** section. Note that the new *Nodes section is called **Advanced Options** as discussed in the ticket referenced above.
- Does the NodeFamily option belong to the new Advanced Options section? I haven't moved it yet because I wanted to check before moving it.

#32928#32929:Tor Manual: Added New sections for Timeout and Node Options

---

.travis.yml
changes/ticket33075

Stop allowing failures on the Travis CI stem tests job. It looks like
all the stem hangs we were seeing are now fixed, but let's make sure we
see them if they happen again.
Closes ticket 33075.

Travis: Stop allowing stem test failures

---

changes/bug33284
scripts/git/pre-push.git-hook

Stop executing the checked-out pre-commit hook from the pre-push hook.
Instead, execute the copy in the user's git dir.
Fixes bug 33284; bugfix on 0.4.1.1-alpha.

scripts/git: Stop running the checked-out git scripts

---

changes/ticket33339
scripts/maint/checkManpageAlpha.py

Add a script to help check the alphabetical ordering of option names
in a manpage.  Closes ticket 33339.

ticket33339 Script to check sorting of manpage entries

---

changes/ticket33192
contrib/client-tools/tor-resolve.py
scripts/codegen/fuzzing_include_am.py
scripts/codegen/gen_server_ciphers.py
scripts/codegen/get_mozilla_ciphers.py
scripts/codegen/makedesc.py
scripts/maint/annotate_ifdef_directives.py
scripts/maint/checkIncludes.py
scripts/maint/format_changelog.py
scripts/maint/lintChanges.py
scripts/maint/locatemissingdoxygen.py
scripts/maint/practracker/includes.py
scripts/maint/practracker/metrics.py
scripts/maint/practracker/practracker.py
scripts/maint/practracker/practracker_tests.py
scripts/maint/rectify_include_paths.py
scripts/maint/redox.py
scripts/maint/sortChanges.py

This proposed change will change all occasions of `/usr/bin/python` to the more agnostic `/usr/bin/env python`, similarly to the change [here](https://github.com/torproject/tor/commit/a10d4adc25500e160c71d0d3f32a6f3ebbf3c9fd).
[Relevant Trac ticket](https://trac.torproject.org/projects/tor/ticket/33192#ticket) (Fixes 33192)
This pull request is a follow up to #1712 and was made due to issues regarding the tree that was used to make the changes. More information about this can be found in the Trac ticket itself. Some of the changes were adapted accordingly, but they are identical for the most part.

Stop assuming that /usr/bin/python exists

---

.travis.yml
changes/ticket32792

When a Travis chutney job fails, use chutney's new "diagnostics.sh" tool
to produce detailed diagnostic output.
Closes ticket 32792.

Travis: Produce detailed chutney diagnostics

---

changes/bug33374
scripts/maint/practracker/practracker.py

Allow the "practracker" coding best practices checking script to read
unicode files, when using Python 2.
We made the script use unicode literals in 0.4.3.1-alpha, but didn't
change the codec for opening files.
Fixes bug 33374; bugfix on 0.4.3.1-alpha.

practracker: Read unicode files when using Python 2

---

doc/tor.1.txt

- Added a TOC for easy scrolling on the HTML page.
- Standardized the cross-reference format and added hyperlinks to all cross-refs within the doc.

#33369:Added TOC and hyperlinks for cross-refs

---

changes/ticket32720
src/core/or/status.c
src/feature/control/control_bootstrap.c
src/feature/control/control_events.h
src/feature/dirclient/dirclient.c
src/feature/dirclient/dirclient.h

Remember dirctory bw usage, and log it in the heartbeat

---

changes/bug33531
src/core/or/circuituse.c

Fixes bug 33531; bugfix on 0.3.3.1-alpha.

Remove surprising empty line in info-level cbt log

---

changes/bug33093_logging
src/lib/tls/buffers_tls.c

We introduced these BUG() checks in b0ddaac07428a06 to prevent a
recurrence of bug 23690.  But there's a report of the BUG() message
getting triggered and filling up the disk.  Let's change it to
IF_BUG_ONCE().
Fixes bug 33093; bugfix on 0.3.2.2-alpha.

Change BUG() messages in buf_flush_to_tls() to IF_BUG_ONCE()

---

src/test/test_circuitbuild.c
src/test/test_dir.c

Closes bug 33641; not in any released version of tor.

coverity: Silence spurious unreachable warning

---

src/test/test_policy.c

Ticket: https://trac.torproject.org/projects/tor/ticket/33555

[Tor Trac #33555]: Space out the line.key/line.value in test_policy_summary_helper_family_flags()

---

changes/ticket33678_043
scripts/maint/practracker/.enable_practracker_in_hooks

Disable our coding standards best practices tracker in our git hooks.
0.4.3 branches only.
Closes ticket 33678.

practracker: Disable practracker in git hooks

---

.appveyor.yml
changes/bug33673

Copy required DLLs to test and app, before running tor's tests.
This ensures that tor.exe and test*.exe use the correct version of each
DLL. This fix is not required, but we hope it will avoid DLL search
issues in future.
Closes bug 33673; bugfix on 0.3.4.2-alpha.

Appveyor: Copy required DLLs to test and app

---

changes/bug33608
src/core/mainloop/connection.c

Stop forcing all non-SOCKSPorts to prefer IPv6 exit connections.
Instead, prefer IPv6 connections by default, but allow users to change
their configs using the "NoPreferIPv6" port flag.
Fixes bug 33608; bugfix on 0.4.3.1-alpha.

connection: Stop forcing some ports to prefer IPv6

---

src/feature/nodelist/routerlist.c

See [ticket 33573](https://trac.torproject.org/projects/tor/ticket/33573).
Descriptor differences are cosmetic if 2 hours has passed, not 12 hours.

Update comment in router_differences_are_cosmetic()

---

src/feature/hs/hs_ob.c

This is to allow a visual feedback in the logs for operators setting up Onion
Balance so they can confirm they properly configured the instances.

hs-v3: Move to log notice the registration of an OB instance

---

changes/ticket33779
src/feature/hs/hs_service.c

hs-v3: Fix typo in log info when PublishHidServDescriptors is set to 0

---

changes/ticket33491
src/core/or/channel.c
src/core/or/dos.c
src/core/or/dos.h
src/test/test_dos.c

For a bridge configured with a pluggable transport, the transport name is
used, with the IP address, for the GeoIP client cache entry.
However, the DoS subsystem was not aware of it and always passing NULL when
doing a lookup into the GeoIP cache.
This resulted in bridges with a PT are never able to apply DoS defenses for
newly created connections.
Fixes #33491

dos: Pass transport name on new client connection

---

changes/bug34077
src/feature/dirauth/shared_random_state.c

Fixes 34077 for 0.4.1; bugfix on 0.4.0.3-alpha. (Specifically, GCC
first gives this warning for 9eeff921ae7b786d960ea4286d5bba56)

Fix a GCC 10.0.1 compilation warning.

---

changes/ticket33778
doc/tor.1.txt
src/app/config/testnet.inc

See [ticket #33778](https://trac.torproject.org/projects/tor/ticket/33778).
>  A few of the values under `TestingTorNetwork` in `doc/tor.1.txt` are out of date compared to the options in `src/app/config/testnet.inc`. Also, some of the units listed for options only state 'minutes|hours' when they actually support 'seconds' as well. I only fixed the ones that were relevant to `TestingTorNetwork`, but there are probably others as well.

Updated the TestingTorNetwork man page options

---

changes/ticket34211
src/app/main/main.c

This pull request is for Ticket [#34211](https://trac.torproject.org/projects/tor/ticket/34211):
> Hi everyone!
> 
> I am working on a [cross-platform Tor controller/wrapper](https://github.com/DcodingTheWeb/ProxAllium/tree/next-gen), and I encountered a minor inconvenience while writing code for stopping Tor in Windows.
> 
> Currently the only way to gracefully terminate Tor in Windows is to use the control port to issue the `SIGINT` signal, it would be beneficial for 3rd party programs which work with Tor to be able to invoke this procedure by using the native "control signals" provided to console programs in Windows.
> 
> I have made a patch which implements this functionality, I will post it soon, I am creating this ticket so that I can create a corresponding file in the `changes` …

Add support for console control signals in Windows

---

src/feature/hs/hs_service.c

The warning was:
11:23:10 ../tor/src/feature/hs/hs_service.c: In function 'log_cant_upload_desc':
11:23:10 ../tor/src/feature/hs/hs_service.c:3118:3: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
See #34254 for more info.
I guess this means that gcc assigned an unsigned type to the
`log_desc_upload_reason_t` enum and it warned if we compared it against 0...
For now I think it's simpler to remove that check instead of turning the enum
to a signed type, or trying to hack it some other way.
From what it seems, enum is up to the compiler on whether it's signed/unsigned:
https://stackoverflow.com/questions/159034/are-c-enums-signed-or-unsigned

Fix an enum comparison that was blowing up jenkins.

---

changes/bug34299
doc/tor.1.txt

Bugfix on 0.2.6.3-alpha; fixes bug 34299.

Man page: MinUptimeHidServDirectoryV2 defaults to 96 hours

---

doc/HACKING/CodingStandards.md

Make clear that Tor's C code targets C99 standards. This makes it more
explicit what to expect for new code, because guessing from existing
code is not always reliable, especially for code that predates the
change in standard.

Documentation: Specify C99 coding standards

---

changes/ticket33788
src/app/config/resolve_addr.c
src/core/or/connection_edge.c
src/feature/client/circpathbias.c
src/feature/control/control_getinfo.c
src/feature/dirauth/dirvote.c
src/feature/nodelist/authcert.c
src/feature/nodelist/dirlist.c
src/feature/nodelist/fmt_routerstatus.c
src/feature/relay/dns.c
src/feature/relay/relay_periodic.c
src/feature/relay/router.c
src/feature/relay/selftest.c
src/feature/rend/rendservice.c
src/lib/net/address.c

https://trac.torproject.org/projects/tor/ticket/33788

#33788: Make things safer when tor_inet_ntop() and tor_inet_ntoa() fail (2)

---

.gitignore

The files contrib/dist/tor.sh and contrib/dist/suse/tor.sh should not
exist anymore, but when building in same repository for older versions
of Tor, these files may return and not be cleaned up properly. This
commit unignores those files from .gitignore, in order to make it clear
that these files are no longer auto-generated and should be cleaned up.
Part of [Trac ticket #34381](https://trac.torproject.org/projects/tor/ticket/34381)

#34381: Remove tor.sh from .gitignore

---

scripts/maint/checkShellScripts.sh

Per <https://trac.torproject.org/projects/tor/ticket/34381>, these
contrib scripts were generated by older versions of Tor and shellcheck
will throw warnings if they still exist.

scripts/maint: Remove obsolete generated tor.sh

---

.travis.yml

This reverts commit e63bfca5f2d98788d11b9a0a82bf67277a228c71, now
that Stem has been upgraded to fix the underlying issue.

Revert "Travis: temporarily fix stem version to d1174a83c2dcb7b8"

---

changes/ticket34382
src/lib/sandbox/sandbox.c

M_SYSCALL is used to report information about a sandbox violation,
but when we don't have a definition for it, it still makes sense to
compile.
Closes ticket 34382.

sandbox: Do not require M_SYSCALL.

---

src/feature/control/control_getinfo.c
src/feature/relay/relay_periodic.c
src/feature/relay/router.c
src/feature/relay/selftest.c
src/feature/relay/selftest.h
src/feature/stats/predict_ports.c

These identifiers are confusing and unreadable.  I think these
replacements should be better. Closes ticket #40012.
This is an automated commit, generated by this command:
./scripts/maint/rename_c_identifier.py \
router_should_skip_orport_reachability_check_family router_orport_seems_reachable \
router_should_skip_dirport_reachability_check router_dirport_seems_reachable \
router_should_skip_dirport_reachability_check router_all_orports_seem_reachable

Replace router_should_skip_*() identifiers.

---

src/app/config/resolve_addr.c

addr: Look at /48 for IPv6 in is_local_addr()

---

changes/bug33032
src/lib/encoding/pem.c
src/test/test_pem.c

Fixes bug 33032; bugfix on 0.3.5.1-alpha when we introduced our own
PEM decoder.

pem_decode(): Tolerate CRLF line endings

---

changes/bug34303
src/core/or/circuitlist.c
src/feature/client/entrynodes.c

Resume being willing to use preemptively-built circuits when
UseEntryGuards is set to 0. We accidentally disabled this feature with
that config setting (in our fix for #24469), leading to slower load times.
Fixes bug 34303; bugfix on 0.3.3.2-alpha.

Preemptive circs should work with UseEntryGuards 0

---

changes/ticket34445
doc/tor.1.txt
src/feature/dirauth/dirauth_options.inc
src/feature/dirauth/reachability.c
src/feature/dirauth/voteflags.c

AssumeReachable should only be about whether a relay thinks that it
is reachable itself.  But previously, we've had it also turn off
reachability checking of _other_ relays on authorities.
(Technically, reachability tests were still run, but we would ignore
the results.)
With this patch, there is a new AuthDirTestReachability option
(default 1) that controls whether authorities run reachability
tests.
Making this change allows us to have test networks where authorities
set AssumeReachable without disabling their reachability testing
entirely.
Closes ticket #34445.

Remove special authority semantics for AssumeReachable.

---

changes/ticket34137
src/core/or/circuitbuild.c
src/feature/relay/relay_config.c
src/feature/relay/selftest.c
src/feature/relay/selftest.h

Previously we had two chains of logic for reachability tests: one
for launching them, and one for telling the user that we had
launched them.  Now, we simply have the launch code inform the user:
this way, we can't get out of sync.
Closes ticket 34137.

Refactor reachability test logging: log exactly what we launch.

---

changes/bug16016
src/feature/nodelist/routerlist.c

This is not actually a bug!  It can happen for a bunch of reasons,
which all boil down to "trying to add an extrainfo for which we no
longer have the corresponding routerinfo".
Fixes #16016; bugfix on 0.2.6.3-alpha.

Downgrade "Bug: No entry found in extrainfo map" message.

---

src/app/config/resolve_addr.c
src/test/test_config.c

Unit tests also suffered from a memleak.
Closes #40024

addr: Fix possible memleak in find_my_address()

---

.appveyor.yml
changes/ticket40026

For some reasons, Appveyor started to use the stdio printf format for 64 bit
values (PRIu64, ...). Mingw doesn't like that so force it to use the Windows
specific macros by setting D__USE_MINGW_ANSI_STDIO=0.
Fixes #40026

CI: Fix Appveyor printf format error

---

changes/ticket33236
src/app/config/resolve_addr.c
src/app/config/resolve_addr.h
src/test/test_config.c

If no Address statement are found in the configuration file, attempt to learn
our address by looking at the ORPort address if any. Specifying an address is
optional so if we can't find one, it is fine, we move on to the next discovery
mechanism.
Note that specifying a hostname on the ORPort is not yet supported at this
commit.
Closes #33236

addr: Attempt to learn our address with ORPort

---

changes/bug40028
src/lib/tls/x509.c

This warning only affects platforms (like win32) with 32-bit time_t.
Fixes bug 40028; bugfix on 0.3.2.8-rc.

Resolve a compiler warning from a 32-bit signed/unsigned comparison

---

changes/ticket33873
src/core/or/connection_edge.c
src/test/test_hs_common.c

This commit modifies the behavior of `parse_extended_address` in such a way
that if it fails, it will always return a `BAD_HOSTNAME` value, which is then
used to return the 0xF6 extended error code.  This way, in any case that is
not a valid v2 address, we return the 0xF6 error code, which is the expected
behavior.

socks: Returns 0xF6 only if BAD_HOSTNAME

---

changes/ticket33796
doc/tor.1.txt
src/app/config/config.c
src/test/test_config.c

This reverts commit bf2a399fc0d90df76e091fa3259f7c1b8fb87781.

Revert "config: Make clients tell dual-stack exits they prefer IPv6"

---

changes/ticket34087
src/feature/hs/hs_client.c

When receiving an introduction NACK, the client either decides to close or
re-extend the circuit to another intro point.
In order to do this, the service descriptor needs to exists but it is possible
that it gets removed from the cache between the establishement of the
introduction circuit and the reception of the (N)ACK.
For that reason, the BUG(desc == NULL) is removed because it is a possible
normal use case. Tor recovers gracefully already.
Fixes #34087

hs-v3: Remove a possible BUG() condition

---

src/feature/relay/relay_find_addr.c

Fix on unreleased code.
The relay_new_address_suggestion() is called when a NETINFO cell is received
thus not only for relay or bridges.
Remove the BUG() that made sure only in server mode we could handle the
suggested address.
Fixes #40032

addr: Remove a BUG() that can normally occur

---

src/app/config/resolve_addr.c

Fix on unreleased code.
Logical || in the BUG() made it that it would always trigger the BUG().
Fixes #40034

addr: Remove BUG() that always triggers

---

src/feature/nodelist/describe.c
src/feature/nodelist/describe.h
src/test/test_nodelist.c

Pass the IPv4 before the IPv6 like all our other interfaces.
Changes unreleased code related to #40043.
Closes #40045

node: Standardize interface of format_node_description()

---

changes/feature40047
scripts/maint/practracker/exceptions.txt
src/app/config/config.c
src/app/main/main.c
src/lib/osinfo/include.am
src/lib/osinfo/libc.c
src/lib/osinfo/libc.h
src/test/conf_examples/crypto_accel/expected_log_nss
src/test/conf_examples/crypto_accel_req/expected_log_nss
src/test/conf_examples/lzma_zstd_1/expected_log
src/test/conf_examples/lzma_zstd_1/expected_log_lzma
src/test/conf_examples/lzma_zstd_1/expected_log_lzma_zstd
src/test/conf_examples/lzma_zstd_1/expected_log_zstd
src/test/conf_examples/nss_1/expected_log
src/test/conf_examples/nss_1/expected_log_nss
src/test/test_parseconf.sh

Adds the running glibc version to the log. Also adds the running and compiled glibc version to the library list returned when using the flag --library-versions.

[Tor Gitlab #40047]: Add running glibc version to the log

---

doc/man/tor.1.txt
src/app/config/config.c
src/app/config/or_options_st.h
src/app/config/resolve_addr.c
src/feature/relay/relay_find_addr.c
src/test/test_config.c
src/test/test_relay.c

This option controls if a tor relay will attempt address auto discovery and
thus ultimately publish an IPv6 ORPort in the descriptor.
Behavior is from proposal 312 section 3.2.6.
Closes #33245

relay: Add AddressDisableIPv6 torrc option

---

src/feature/relay/router.c

The ORPort can be IPv4Only which means that even if we can auto discover an
IPv6 address, we should not publish it because it would have an ORPort of 0.
Fixes #40054

relay: Don't publish IPv6 if found ORPort is 0

---

changes/ticket33220
src/core/or/extendinfo.c

(This is not fully general yet: we only pick randomly among
_supported_ addresses, and each extendinfo contains at most one IPv4
address and at most one IPv6 address, no matter what the extend cell
had.)
This change will help dual-stack relays do IPv6 reachability tests,
in theory, by having them sometimes do IPv4 connections and
sometimes do ipv6 connections.
Closes ticket 33220.

When choosing an orport from an extendinfo, pick randomly.

---

src/feature/dirclient/dirclient.c

log: Don't use twice fmt_addr() in same logging statement

---

src/feature/control/control_cmd.c

Ticket: https://gitlab.torproject.org/tpo/core/tor/-/issues/40029

[GitLab #40029]: Remove duplicate #include control_events.h in control_cmd.c

---

changes/bug31036
src/lib/fdio/fdio.c

Fixes bug 31036; bugfix on 0.2.1.8-alpha when we moved the logging
system to use posix fds.

Use _lseeki64() on windows.

---

changes/ticket32190
src/core/or/connection_edge.c
src/core/or/connection_edge.h
src/feature/control/control_cmd.c
src/feature/control/control_events.c
src/feature/control/control_events.h

Ticket: https://gitlab.torproject.org/tpo/core/tor/-/issues/32190

[GitLab #32190]: Send a control port event when a stream enters the controller_wait state

---

changes/ticket40081
src/core/or/channel.c
src/core/or/channel.h
src/core/or/channeltls.c
src/core/or/circuitbuild.c
src/test/test_channel.c

This function once served to let circuits continue to be built over
version-1 link connections.  But such connections are long-obsolete,
and it's time to remove this check.
Closes #40081.

Remove channel_is_canonical_is_reliable()

---

changes/bug40099
src/test/test_rendcache.c

Without this fix, running this test on its own would fail.
Fixes bug 40099. Bugfix on ade5005853c17b3 in 0.2.8.1-alpha.

Fix allocation counting in clean_v2_descs_as_dir test.

---

changes/ticket40102
scripts/maint/practracker/exceptions.txt
src/app/config/config.c

Split implementation of several command line options from
options_init_from_torrc into smaller isolated functions.

[Tor Gitlab #40102]: Make options_init_from_torrc smaller

---

changes/bug19431
src/lib/log/ratelim.c
src/lib/log/ratelim.h
src/test/test_logging.c

Previous message would say "N messages in the last T seconds", but
would give an inaccurate number for N.
We now give an accurate number, rounded up to the nearest 60 seconds.
Closes #19431.

Improve ratelimit message to list true interval.

---

changes/bug40105
src/feature/client/entrynodes.c

Avoid guard-related warning when upgrading from 043 to 044.

---

changes/bug20165
src/core/or/channel.c
src/core/or/channel.h
src/core/or/channeltls.c
src/feature/relay/circuitbuild_relay.c
src/feature/relay/router.c
src/feature/relay/router.h

Previously, we would treat *any* incoming circuit on a non-local
channel as meaning that our ORPort was reachable.  With this patch,
we make sure that the address that the peer _says_ we have is the
same as the one we're trying to advertise right now.
Closes 20165. Bugfix on 4f5192b2803c706 in 0.1.0.1-rc, when
reachability self-tests were first introduced.

Validate address more carefully when checking self-reachability

---

changes/bug40117
src/feature/rend/rendmid.c

tl;dr We were not counting cells flying from the client to the service, but we
were counting cells flying from the service to the client.
When a rendezvous cell arrives from the client to the RP, the RP forwards it to
the service.
For this to happen, the cell first passes through command_process_relay_cell()
which normally does the statistics counting. However because the `rend_circ`
circuit was not flagged with `circuit_carries_hs_traffic_stats` in
rend_mid_rendezvous(), the cell is not counted there.
Then the cell goes to circuit_receive_relay_cell() which has a special code
block based on `rend_splice` specifically for rendezvous cells, and the cell
gets directly passed to `rend_circ` via a direct call to
circuit_receive_relay_cell(). The cell never passes through …

statistics: Properly count all rendezvous cells (avoid undercounting).

---

changes/ticket40125
src/test/test_rendcache.c

The rend_cache/entry_free was missing the rend cache allocation increment
before freeing the object.
Without it, it had an underflow bug:
Sep 17 08:40:13.845 [warn] rend_cache_decrement_allocation(): Bug: Underflow
in rend_cache_decrement_allocation (on Tor 0.4.5.0-alpha-dev
7eef9ced61e72b1d)
Fixes #40125

test: Increment rend cache allocation before freeing

---

changes/ticket40073
src/core/mainloop/connection.c

Opening a new listener connection can fail in many ways like a bind()
permission denied on a low port for instance.
And thus, we should expect to handle an error when creating a new one instead
of assert() on it.
To hit the removed assert:
ORPort 80
KeepBindCapabilities 0
Start tor. Then edit torrc:
ORPort <some-IP>:80
HUP tor and the assert is hit.
Fixes #40073

conn: Remove assert on new listener connection when retrying

---

changes/log_32868
src/feature/nodelist/node_select.c

We hit this assertion with bug 32868, but I'm stymied figuring out
how we wound up with a routerstatus like this.  This patch is a
diagnostic to attempt to figure out what is going on, and to avoid a
crash in the meantime.

Replace an assertion with a check-and-log

---

changes/ticket33747
src/core/mainloop/connection.c
src/core/or/connection_st.h
src/feature/relay/ext_orport.c

Without this fix, if an PT forgets to send a USERADDR command, that
results in a connection getting treated as local for the purposes of
rate-limiting.
If the PT _does_ use USERADDR, we still believe it.
Closes ticket 33747.

Treat all extorport connections with un-set addresses as remote

---

changes/ticket33880
src/core/or/channel.c

Previously we tolerated up to 1.5 connections for every relay we
were connected to, and didn't warn if we had fewer than 5
connections total.
Now we tolerate up to 1.5 connections per relay, and up to 4
connections per authority, and we don't warn at all when we have
fewer than 25 connections total.
Fixes bug 33880, which seems to have been provoked by our #17592
change in 0.3.5.

Adjust the rules for warning about too many connections.

---

changes/bug40141
src/lib/fs/path.c

Fix bug where %including a pattern ending in */ would include
files and folders (instead of folders only) in versions of
glibc < 2.19.

[Tor Trac #40141]: Fix %include bug with pattern with */ on glibc < 2.19

---

changes/ticket40164
doc/tor.1.txt
src/feature/dirauth/dirauth_options.inc
src/feature/dirauth/dirvote.c

Make it possible to specify multiple ConsensusParams torrc
lines.
Now directory authority operators can for example put the
main ConsensusParams config in one torrc file and then add to it
from a different torrc file.
Closes ticket 40164.

Turn ConsensusParams into a Linelist

---

changes/ticket40133
src/core/or/protover.c
src/rust/protover/errors.rs
src/rust/protover/protoset.rs
src/rust/protover/protover.rs
src/rust/protover/tests/protover.rs
src/test/test_protover.c

In brief: we go through a lot of gymnastics to handle huge protover
numbers, but after years of development we're not even close to 10
for any of our current versions.  We also have a convenient
workaround available in case we ever run out of protocols: if (for
example) we someday need Link=64, we can just add Link2=0 or
something.
This patch is a minimal patch to change tor's behavior; it doesn't
take advantage of the new restrictions.
Implements #40133 and proposal 318.

Implement proposal 318: Limit protovers to 0..63

---

changes/ticket18888
src/app/main/include.am
src/app/main/main.c
src/app/main/risky_options.c
src/app/main/risky_options.h

These options are meant for testing builds only, and are likely to
cause trouble if used in a production environment.
Closes #18888.

Log a warning if Tor was built with any "risky" compile-time options

---

changes/bug40187
src/test/test_helpers.c

Fixes bug 40187; bugfix on 0.4.5.1-alpha.

Fake the current time when we're loading TEST_DESCRIPTORS.

---

changes/bug40179_part1
src/test/hs_ntor_ref.py

Previously, hashlib.shake_256 was a class (if present); now it can
also be a function.  This change invalidated our old
compatibility/workaround code, and made one of our tests fail.
Fixes bug 40179; bugfix on 0.3.1.6-rc when the workaround code was
added.

Handle a change in the implementation of hashlib in Python 3.9

---

changes/ticket40195
src/feature/relay/relay_config.c

The function in charge of removing duplicate ORPorts from our configured ports
was skipping all non ORPorts port but only for the outer loop thus resulting
in comparing an ORPort with a non-ORPort which lead to problems.
For example, tor configured with the following would fail:
ORPort auto
DirPort auto
Both end up being the same configuration except that one is a OR listener and
one is a Dir listener. Thus because of the missing check in the inner loop,
they looked exactly the same and thus one is removed.
Fixes #40195

config: Really ignore non ORPorts when removing duplicates

---

changes/ticket40142
src/core/or/sendme.c

When sending the stream level SENDME, it is possible the cirucit was marked
for close or any other failures that can occur. These events can occur
naturally.
Fixes #40142

sendme: Turn log warning into debug

---

changes/ticket25528
src/app/config/config.c
src/feature/client/bridges.c
src/feature/client/bridges.h

config: Bridge line with a transport must have a ClientTransportPlugin

---

changes/ticket40017_redux
src/core/or/connection_or.c

This shouldn't be possible, but let's add it for defense-in-depth.
Closes #40017.

Detect extra bytes in HAProxy inbuf when transitioning to OR handshake

---

changes/ticket17927
src/lib/lock/compat_mutex.h
src/lib/lock/compat_mutex_winthreads.c
src/lib/thread/compat_winthreads.c

Replace the Windows locking implementation which used critical
sections with the faster SRWLocks available since Vista.

[Tor Trac #17927]: Use SRWLocks to implement locking on Windows

---

src/test/test_util.c

On the parisc/hppa architecture, the O_NONBLOCK constant can be either
000200000 or 000200004, depending on the Linux kernel and glibc version
on which the binary is running.
Background of this can be read in this upstream Linux kernel patch:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=75ae04206a4d0e4f541c1d692b7febd1c0fdb814
The tor testcases fail because of this, because function
fd_is_nonblocking() checks hard against the O_NONBLOCK value, while it's
sufficient if it would only check if one of the bits is set.
Fix this trivial issue by just comparing if the returned file descriptor flag
and'ed with O_NONBLOCK is non-zero.
As reference, a failing build on parisc/hppa can be seen here:
https://buildd.debian.org/status/fetch.php?pkg=tor&arch=hppa&ver=0.4.4 …

Fix testcases regarding O_NONBLOCK on parisc/hppa architecture
