- .travis.yml
- changes/coveralls
> Add support for the coveralls.io coverage tool in travis config

- changes/ticket26064
- src/or/hibernate.c
- src/or/hibernate.h
- src/or/main.c
> Give responsibility for waking up from DORMANT to a mainloop event

- changes/bug25852
- src/or/policies.c
- src/or/router.c
- src/or/router.h
- src/test/test_policy.c
https://trac.torproject.org/projects/tor/ticket/25852
> Bug25852 take2

- changes/bug26283
- src/or/routerlist.c
https://trac.torproject.org/projects/tor/ticket/26283
> Silence -Wbad-function-cast warning (when DEBUG_SMARTLIST is on)

- changes/bug24891
- src/common/include.am
- src/or/include.am
- src/test/include.am
- src/trunnel/include.am
https://trac.torproject.org/projects/tor/ticket/24891
> #24891: Heed --disable-unittests properly

- changes/bug26282
- src/common/util.c
- src/or/control.c
- src/or/geoip.c
https://trac.torproject.org/projects/tor/ticket/26282
> #26282: Avoid casting smartlist index implicitly

- changes/bug25477
- src/or/rendcache.c
https://trac.torproject.org/projects/tor/ticket/25477
> #25477: Refrain from mentioning old bug in a warning

- changes/feature8323
- src/or/control.c
- src/test/test_controller.c
https://trac.torproject.org/projects/tor/ticket/8323
> Implement GETINFO md/all

- changes/ticket26527
- src/lib/cc/compat_compiler.h
- src/lib/fs/mmap.h
- src/lib/malloc/util_malloc.h
- src/lib/string/compat_string.h
- src/lib/string/printf.h
- src/lib/string/util_string.h
https://trac.torproject.org/projects/tor/ticket/26527
> #26527: Remove ATTR_NONNULL macro

- changes/bug26525
- src/lib/net/address.c
- src/lib/net/resolve.c
- src/lib/net/resolve.h
- src/lib/sandbox/sandbox.c
- src/or/main.c
https://trac.torproject.org/projects/tor/ticket/26525
> #26525: Rename sandbox_getaddrinfo() et. al.

- CODE_OF_CONDUCT
- CONTRIBUTING
- Makefile.am
- changes/doc26638
https://trac.torproject.org/projects/tor/ticket/26638
> #26638: Add CODE_OF_CONDUCT file

- changes/bug26715
- src/core/or/connection_edge.c
- src/lib/net/ipv6.h
For [Tor Trac #26715](https://trac.torproject.org/projects/tor/ticket/26715),
> [Trac #26715]: Fix build on FreeBSD post-refactor

- changes/ticket26663
- src/app/config/config.c
- src/app/config/confparse.c
- src/test/test_config.c
https://trac.torproject.org/projects/tor/ticket/26663
> #26663: Made 'auto' keyword in torrc case insensitive

- changes/bug26789
- scripts/codegen/fuzzing_include_am.py
- src/test/fuzz/include.am
- src/test/include.am
https://trac.torproject.org/projects/tor/ticket/26789
> #26789: Fix build to work with --disable-unittests again (0.3.4)

- Makefile.am
- changes/bug26789
- scripts/codegen/fuzzing_include_am.py
- src/test/fuzz/include.am
- src/test/include.am
https://trac.torproject.org/projects/tor/ticket/26789
> #26789: Fix build to work with --disable-unittests again

- .gitignore
- changes/feature19506
- doc/include.am
- doc/tor-print-ed-signing-cert.1.txt
- src/tools/Makefile.nmake
- src/tools/include.am
- src/tools/tor-print-ed-signing-cert.c
https://trac.torproject.org/projects/tor/ticket/19506
> #19506:  Tool to print expiration date of ed25519_signing_cert (2)

- src/lib/string/printf.c
- src/test/test_util.c
> Increase line coverage in libtor-string to 100%

- changes/bug20424_029_minimal
- configure.ac
> When setting a nonstandard malloc, disable the system malloc.

- changes/bug27034
- src/feature/relay/router.c
- src/test/test_policy.c
https://trac.torproject.org/projects/tor/ticket/27034
> #27034 Minor fixes regarding routerinfo error handling

- changes/bug26882
- doc/tor.1.txt
- src/core/or/channeltls.c
https://trac.torproject.org/projects/tor/ticket/26882
> #26882: Scrub IP in channel_tls_process_netinfo_cell()

- INSTALL
- changes/doc26588
https://trac.torproject.org/projects/tor/ticket/26588
> #26588: Remove old instructions from INSTALL

- changes/doc26908
- doc/tor.1.txt
- src/config/torrc.minimal.in-staging
- src/config/torrc.sample.in
https://trac.torproject.org/projects/tor/ticket/26908
> #26908: Warn users that they should not include MyFamily line(s) in their torrc when running Tor bridge

- changes/bug27044
- doc/tor.1.txt
- src/feature/rend/rendservice.c
- src/test/test_controller.c
- src/test/test_hs_config.c
https://trac.torproject.org/projects/tor/ticket/27044
> #27044: Stricter HiddenServicePort parsing (2)

- changes/ticket8415
- src/core/mainloop/main.c
https://trac.torproject.org/projects/tor/ticket/8415
> #8415: Call event_set_mem_functions during initialization

- changes/bug27428
- src/app/config/config.c
- src/lib/string/util_string.c
- src/lib/string/util_string.h
- src/test/test_util.c
https://bugs.torproject.org/27428
> [#27428] Unicode contactinfo1

- changes/ticket25573
- src/core/include.am
- src/core/or/circuitbuild.c
- src/core/or/circuitbuild.h
- src/core/or/circuitlist.c
- src/core/or/connection_edge.c
- src/core/or/connection_edge.h
- src/core/or/half_edge_st.h
- src/core/or/origin_circuit_st.h
- src/core/or/relay.c
- src/feature/client/circpathbias.c
- src/feature/client/circpathbias.h
- src/lib/container/smartlist.c
- src/lib/container/smartlist.h
- src/test/test_relaycell.c
Ticket 25573 merged to master.
> Ticket25573 master

- changes/bug27165
- src/core/or/channelpadding.c
- src/feature/stats/rephist.c
- src/lib/time/tvdiff.c
- src/lib/time/tvdiff.h
https://trac.torproject.org/projects/tor/ticket/27165
> #27165: Try fixing CID 1438153

- src/core/or/circuitbuild.c
http://ea5faa5po25cf7fb.onion/projects/tor/ticket/27333
> Update description of onion_extend_cpath() (#27333)

- changes/bug27675
- src/test/test_rebind.py
https://trac.torproject.org/projects/tor/ticket/27675
> #27675: Tweak test_rebind.py (2)

- changes/doc27853
- doc/tor-resolve.1.txt
https://trac.torproject.org/projects/tor/ticket/27853
> #27853: Fix reference to socks-extensions.txt in tor-resolve manpage

- changes/bug27808
- src/core/mainloop/connection.c
https://trac.torproject.org/projects/tor/ticket/27808
> #27808:  Make sure we're removing conn from old_conns at most once

- changes/bug27928
- src/core/mainloop/connection.c
https://trac.torproject.org/projects/tor/ticket/27928
> #27928: Refrain from listener rebinding when address families differ (2)

- changes/ticket27625
- src/test/include.am
- src/test/test.c
- src/test/test.h
- src/test/test_parsecommon.c
https://trac.torproject.org/projects/tor/ticket/27625
> #27625: Write unit tests for tokenize_string() and get_next_token()

- changes/ticket28006
- scripts/test/chutney-git-bisect.sh
https://trac.torproject.org/projects/tor/ticket/28006
> #28006: Fix issues that shellcheck found in chutney-git-bisect.sh

- changes/ticket28010
- scripts/codegen/run_trunnel.sh
https://trac.torproject.org/projects/tor/ticket/28010
> #28010: Fix shellcheck issues in run_trunnel.sh

- changes/ticket28011
- scripts/maint/run_calltool.sh
https://trac.torproject.org/projects/tor/ticket/28011
> #28011: Fix shellcheck warnings in run_calltool.sh

- src/rust/protover/ffi.rs
(I messed up the merge in 289a7dbac32a981897e12a3c250f0b6c67eec809.)
> Try to restore a proper fix for bug27740 in 0.3.5.

- changes/bug27929
- src/core/mainloop/mainloop.c
https://trac.torproject.org/projects/tor/ticket/27929
> #27929: Create new periodic event for pruning old info about Tor routers

- changes/bug28518
- src/app/config/config.c
PR for https://trac.torproject.org/28518
> Bug #28518

- src/core/mainloop/connection.c
- src/test/test_rebind.py
https://trac.torproject.org/projects/tor/ticket/28229
> #28229: More diagnostics

- changes/doc28560
- doc/tor.1.txt
https://trac.torproject.org/projects/tor/ticket/28560
> #28560: Mention that adding new HS is unsupported if Sandbox is enabled

- changes/ticket28012
- scripts/maint/updateRustDependencies.sh
https://trac.torproject.org/projects/tor/ticket/28012
> 28012: Fix issues that shellcheck found in updateRustDependencies.sh

- .travis.yml
- changes/ticket28551
https://trac.torproject.org/projects/tor/ticket/28551
> #28551:  Print Python version during each Travis CI job

- changes/ticket28007
- scripts/test/scan-build.sh
https://trac.torproject.org/projects/tor/ticket/28007
> #28007: Address shellcheck warnings in scan-build.sh (2)

- changes/ticket24838
- changes/ticket28768
- scripts/maint/fallback.whitelist
- scripts/maint/updateFallbackDirs.py
* 24838: fuzzy match the fallback whitelist
* 28768: update fallback script to match Tor bootstrap changes
> Ticket24838: fallback script improvements

- changes/document_version
- doc/tor.1.txt
> Document the output of --version

- src/test/test_voting_flags.c
Trac ticket: https://trac.torproject.org/projects/tor/ticket/28939
> Fix buffer overflow in src/test/test_voting_flags.c

- changes/doc28805
- doc/tor.1.txt
https://trac.torproject.org/projects/tor/ticket/28805
> #28805: Tweak ControlPort description in manpage

- changes/ticket28843
- src/feature/control/control.c
> Add a DROPOWNERSHIP controller command to undo TAKEOWNERSHIP.

- changes/ticket28757
- src/feature/control/control.c
https://trac.torproject.org/projects/tor/ticket/28757
> #28757: Completely remove 'GETINFO status/version/num-{concurring,versioning}'

- src/feature/client/transports.c
- src/test/test_pt.c
See: https://bugs.torproject.org/28181
> Rename TYPE to TRANSPORT in PT STATUS messages.

- changes/doc28623
- doc/tor.1.txt
https://trac.torproject.org/projects/tor/ticket/28623
> #28623: Use RFC5737-compliant example IP addresses in manpage when describing MapAddress

- changes/ticket29062
- src/test/test_keygen.sh
https://trac.torproject.org/projects/tor/ticket/29062
> #29062: Fix shellcheck warnings in test_keygen.sh

- changes/ticket29067
- src/test/test_workqueue_cancel.sh
- src/test/test_workqueue_efd.sh
- src/test/test_workqueue_efd2.sh
- src/test/test_workqueue_pipe.sh
- src/test/test_workqueue_pipe2.sh
- src/test/test_workqueue_socketpair.sh
https://trac.torproject.org/projects/tor/ticket/29067
> #29067: Fix SC2086 warning in test_workqueue_*.sh shell scripts

- changes/ticket29071
- contrib/dirauth-tools/nagios-check-tor-authority-cert
https://trac.torproject.org/projects/tor/ticket/29071
> #29071: Fix shellcheck warnings in nagios-check-tor-authority-cert script

- changes/ticket29070
- contrib/client-tools/torify
https://trac.torproject.org/projects/tor/ticket/29070
> #29070: Fix shellcheck warning SC2145 in torify script

- changes/bug29063
- src/test/test_rebind.sh
https://trac.torproject.org/projects/tor/ticket/29063
> #29063: Fix shellcheck warnings in test_rebind.sh

- changes/ticket28816
- src/core/mainloop/connection.c
- src/core/mainloop/connection.h
- src/feature/dircache/dircache.c
- src/feature/dircache/dirserv.c
https://trac.torproject.org/projects/tor/ticket/28816
> #28816: Introduce connection_dir_buf_add() helper function

- autogen.sh
- changes/ticket26069
https://trac.torproject.org/projects/tor/ticket/29069
> #26096: Cleanup shellcheck warnings in autogen.sh

- changes/ticket29068
- src/test/zero_length_keys.sh
https://trac.torproject.org/projects/tor/ticket/29068
> #29068: Fix shellcheck warning in zero_length_keys.sh

- changes/ticket29059
- src/test/fuzz_static_testcases.sh
https://trac.torproject.org/projects/tor/ticket/29059
> #29059: Fix shellcheck warning in fuzz_static_testcases.sh (2)

- changes/ticket29391
- scripts/maint/git-merge-forward.sh
- scripts/maint/git-pull-all.sh
- scripts/maint/git-push-all.sh
> maint: Helpful scripts for tor maintenance

- changes/ticket29064
- src/test/test_rust.sh
https://trac.torproject.org/projects/tor/ticket/29064
> #29064: Fix shellcheck warnings in test_rust.sh

- changes/ticket25614
- src/feature/client/transports.c
> Set TOR_PT_EXIT_ON_STDIN_CLOSE=1 for client transports too.

- src/test/test-network.sh
This reverts commit c346eff223e94b5fbeb6e751a99393fc5f7dd4b0.
> Revert "Walk back from requiring bash"

- changes/ticket29537
- configure.ac
- src/lib/cc/torint.h
- src/test/include.am
- src/test/ptr_helpers.c
- src/test/ptr_helpers.h
- src/test/test.h
- src/test/test_ptr_slow.c
- src/test/test_slow.c
https://trac.torproject.org/projects/tor/ticket/29537
> #29537: Check for possible failures of roundtrip between void * and (unsigned) int

- changes/bug29926
- doc/asciidoc-helper.sh
https://trac.torproject.org/projects/tor/ticket/29926
> #29926: Fix SC2086 warnings in asciidoc-helper.sh

- src/ext/timeouts/.may_include
- src/ext/timeouts/test-timeout.c
- src/ext/timeouts/timeout.c
> Fix checkIncludes warning about "unusual pattern in src/ext/timeouts/"

- changes/bug30002
- src/test/test_key_expiration.sh
https://trac.torproject.org/projects/tor/ticket/30002
> #30002: Fix shellcheck warning in test_key_expiration.sh

- changes/ticket30079
- src/test/fuzz/minimize.sh
https://trac.torproject.org/projects/tor/ticket/30079
> #30079: Fix SC2006 in minimize.sh

- changes/ticket30033
- scripts/git/pre-push.git-hook
https://trac.torproject.org/projects/tor/ticket/30033
> #30033: Call pre-commit hook from pre-push script

- scripts/git/pre-commit.git-hook
Fixes bug 30120; bugfix not in any released Tor.
> Fix pre-commit hook to correctly allow empty changes files.

- changes/ticket30078
- src/test/fuzz/fixup_filenames.sh
https://trac.torproject.org/projects/tor/ticket/30078
> #30078: Fix shellcheck warnings in fixup_filenames.sh

- changes/bug22210
- scripts/maint/practracker/exceptions.txt
- src/core/or/circuituse.c
For the ticket [here](https://trac.torproject.org/projects/tor/ticket/22210).
> [Tor Trac #22210]: Only call tor_addr_parse() in circuit_is_acceptable() when needed

- src/feature/rend/rendclient.c
This can cause issues if the circuit was repurposed into a padding circuit
instead of closing, since in that case we will wipe off the rend_data.
> Don't access rend data after a circuit has been marked for close.

- .travis.yml
- changes/ticket30213
https://trac.torproject.org/projects/tor/ticket/30213
> #30213: Remove sudo configuration lines from .travis.yml (0.4.0)

- changes/doc30630
- doc/HACKING/ReleasingTor.md
https://trac.torproject.org/projects/tor/ticket/30630
> #30630: Mention Travis/Appveyor/Jenkins URLs in ReleasingTor.md

- src/test/test_rebind.sh
> test: fix a typo in test_rebind.sh

- .travis.yml
- changes/ticket30234
> Travis: Show stem's tor log after failure

- .travis.yml
- changes/ticket30213
https://trac.torproject.org/projects/tor/ticket/30213
> #30213: Remove sudo configuration lines from .travis.yml (0.3.5)

- changes/bug22619
- src/app/config/config.c
- src/test/test_config.c
Fixes bug 22619; bugfix on 0.2.7.2-alpha
> Fix a logic error in deciding whether to accept SessionGroup=

- changes/ticket27530
- configure.ac
> Check whether gcc-hardening is runnable, and log an error if not

- changes/ticket19381
- configure.ac
- doc/include.am
https://trac.torproject.org/projects/tor/ticket/19381
> #19381: Allow excluding documentation from the build

- Makefile.am
Fixes bug 30963; bug not in any released Tor.
> Don't try to shellcheck src/rust/registry

- changes/ticket30889
- src/feature/control/control_auth.c
- src/feature/control/control_cmd.c
- src/feature/control/control_cmd.h
- src/feature/control/control_proto.c
- src/feature/control/control_proto.h
- src/test/test_controller.c
* Clean up a few "easy" uses of lower-level control reply functions
* Fix some onion_helper functions to directly call higher-level control reply functions instead of passing a string out to their callers
> Ticket30889

- .travis.yml
- changes/ticket30102
https://trac.torproject.org/projects/tor/ticket/30102
> #30102:  On Travis, put random data in ~/.torrc

- changes/ticket30921
- src/feature/hs/hs_cache.c
- src/test/test_hs_client.c
> hs-v3: Close intro circuits when cleaning client cache

- .travis.yml
- changes/ticket30213
https://trac.torproject.org/projects/tor/ticket/30213
> #30213: Remove sudo configuration lines from .travis.yml (0.2.9)

- changes/bug30452
- doc/tor.1.txt
- src/app/config/config.c
- src/app/main/main.c
- src/feature/dirauth/authmode.h
> Add a --list-modules command

- changes/ticket30979
- scripts/git/pre-push.git-hook
- scripts/maint/practracker/.enable_practracker_in_hooks
> pre-push hook: Only run practracker when a special file is present

- doc/tor.1.txt
> Fix typos in HiddenServiceExportCircuitID

- changes/ticket24964
- src/feature/dircache/dircache.c
- src/feature/dircommon/directory.c
- src/feature/dircommon/directory.h
- src/test/test_hs_cache.c
> hs-v3: Disallow single hop client to post/get a descriptor

- src/feature/rend/rendmid.c
> hs: Initialize the INTRO2 bucket for legacy intro point

- scripts/maint/practracker/practracker.py
Fixes bug 31828; bugfix on 0.4.2.1-alpha.
> practracker: Fix a typo in the usage message

- scripts/git/git-merge-forward.sh
Obviously correct minor fixes to code that's already been reviewed.
> Git script fix

- src/lib/err/backtrace.c
Fixes bug 32060; bug not in any released version of tor.
Resolves CID 1454761.
> err: Use the correct type for cb_buf

- scripts/git/git-setup-dirs.sh
git-setup-dirs.sh sets up an upstream git repository and worktrees,
so that tor maintainers can do merges.
Closes ticket 29603.
> scripts: Add git-setup-dirs.sh, which sets up maintainer git repos

- configure.ac
> configure: Add --disable-module-relay to summary

- .travis.yml
- changes/ticket32241
> Travis: Use macOS 10.14 with Xcode 11.2

- changes/ticket32277
- doc/tor.1.txt
Contains wording changes and formatting improvements to DESCRIPTION and COMMAND-LINE OPTIONS sections. Based on a patch by Swati Thacker.
> Ticket32277 tor manpage: reword command-line options and description; improve formatting

- src/core/or/circuit_st.h
- src/core/or/circuitlist.c
- src/core/or/circuitlist.h
> circ: Add an handle to circuit_t

- src/test/fakecircs.c
Coverity CID: 1455207
Closes #32376
> test: Handle NULL circuit pointer in new_fake_orcirc

- changes/ticket30920
- src/lib/confmgt/.may_include
- src/lib/confmgt/unitparse.c
- src/lib/intmath/muldiv.c
- src/lib/intmath/muldiv.h
- src/test/test_confparse.c
- src/test/test_util.c
[Trac link](https://trac.torproject.org/projects/tor/ticket/30920)
Nowrap multiplication function has its own commit. That commit has no change file since I was not sure if it needed a changelog for users. If needed I can amend that commit.
> Ticket30920

- changes/doc31853
- doc/HACKING/CodingStandards.md
https://trac.torproject.org/projects/tor/ticket/31853
> #31853: Merge advice from this_not_that.md in torguts repo into our main coding standard doc

- src/test/test_circuitmux.c
Fixes bug 32496; bug not in any released Tor.
> Fix 32-bit warnings in test_circuitmux.c

- changes/ticket32244
- src/core/include.am
- src/feature/relay/relay_periodic.h
> relay: Disable relay_periodic when the relay module is disabled

- changes/ticket32704
- scripts/maint/format_changelog.py
- scripts/maint/sortChanges.py
> Port changelog tools to python 3

- .travis.yml
- changes/ticket32177
- changes/ticket32629
This reverts commit 511aeba8eeb24a953228e00917f64703059a7673.
> Revert "Travis: Disable all but one macOS build"

- src/test/test_hs_client.c
Ticket: https://trac.torproject.org/projects/tor/ticket/32769
> Remove extra space from helper_get_circ_and_stream_for_test() call in test_e2e_rend_circuit_setup()

- src/lib/net/inaddr.c
Ticket: https://trac.torproject.org/projects/tor/ticket/32829
> [Tor Trac #32829] Fix spacing in tor_inet_aton()

- src/lib/net/inaddr.c
Ticket: https://trac.torproject.org/projects/tor/ticket/32889
> [Tor Trac #32889]: Space the a-d unsigned ints in tor_inet_aton()

- changes/ticket32772
- scripts/git/git-merge-forward.sh
- scripts/git/git-pull-all.sh
- scripts/git/git-push-all.sh
- scripts/git/git-setup-dirs.sh
https://trac.torproject.org/projects/tor/ticket/32772
> #32772: remove 0.2.9 series from git scripts

- .travis.yml
- changes/ticket32455
https://trac.torproject.org/projects/tor/ticket/32455
> #32455: run make doxygen on Travis

- changes/ticket32928
- doc/tor.1.txt
> Ticket32928 changes

- changes/ticket33188
- doc/tor.1.txt
Includes a changes file for #1715
> ticket33188: Alphabetized Server Options and Directory Server Options

- doc/tor.1.txt
This PR includes the following changes:
- Alphabetized the Server and Directory Server Options
- Created a new section titled 'Statistics Options'. Pulled out all the stats-related and extra-info related options, and put them into this new section.
> #33188: Alphabetized Server Options and Directory Server Options

- doc/tor.1.txt
Alphabetically sorted the following four option categories:
- DENIAL OF SERVICE MITIGATION OPTIONS
- DIRECTORY AUTHORITY SERVER OPTIONS
- HIDDEN SERVICE OPTIONS
- TESTING NETWORK OPTIONS
Note the following:
- Exceptions are marked with the //Out of order comment.
- Non-Persistent Options and Client Authorization Options need no changes.
> #33275:Tor Manual:Alphabetically sort the last four sections

- changes/ticket33369
- doc/tor.1.txt
Add a changes file and fix section headings so asciidoc accepts it again.
> Ticket33369 TOC and hyperlinks for cross-refs

- src/feature/relay/dns.c
Ticket: https://trac.torproject.org/projects/tor/ticket/33463
> [Tor Trac #33463]: Correct spacing in dns_launch_correctness_checks()

- changes/doc33417
- doc/tor.1.txt
Also, fix a typo.
https://trac.torproject.org/projects/tor/ticket/33417
> #33417: Refrain from mentioning nicknames in manpage section for MyFamily.

- doc/HACKING/ReleaseSeriesLifecycle.md
> Rename EndOfLifeTor to ReleaseSeriesLifecycle; expand it.

- src/test/test_connection.h
This is a PR for https://trac.torproject.org/projects/tor/ticket/33782
Not sure if it is the right target branch or not. If not, please let me know.
> Increases TEST_CONN_FD_INIT to make tests working on GitHub Actions

- src/feature/relay/router.c
Ticket: https://trac.torproject.org/projects/tor/ticket/33883
> Fix typo in router_build_fresh_unsigned_routerinfo() comment

- .travis.yml
This is a workaround for https://github.com/torproject/stem/issues/63
> Travis: temporarily fix stem version to d1174a83c2dcb7b8

- src/core/or/versions.c
Ticket: https://trac.torproject.org/projects/tor/ticket/34237
> [Tor Trac #34237]: Fix spacing in if statement in tor_version_parse()

- changes/ticket34255_043
- src/lib/conf/confdecl.h
- src/lib/container/smartlist.c
- src/lib/string/compat_ctype.c
- src/lib/wallclock/time_to_tm.c
> Doxygen: fix unbalanced groups.

- src/app/config/config.c
Trac ticket: https://trac.torproject.org/projects/tor/ticket/34236
> [Tor Trac #34236]: Fix spacing in if statement in port_parse_config()

- src/feature/rend/rendservice.c
Ticket: https://trac.torproject.org/projects/tor/ticket/34245
> [Tor Trac #34245]: Declare variables in for loops in rend_service_dump_stats()

- changes/ticket34446
- doc/tor.1.txt
- src/app/config/testnet.inc
> Remove AssumeReachable from TestingTorNetwork.

- changes/ticket28992
- src/feature/hs/hs_client.c
> hs-v3: Remove BUG() that can occur normally

- src/test/test_hs_service.c
Ticket: https://gitlab.torproject.org/tpo/core/tor/-/issues/40004
> [Tor Gitlab #40004]: Fix typo in test_build_update_descriptors() comment

- changes/ticket33361
- src/app/config/config.c
- src/test/test_options.c
> config: Warn if ContactInfo is not set

- changes/bug34357
- src/feature/dirauth/process_descs.c
- src/test/test_process_descs.c
Tor GitLab: https://gitlab.torproject.org/tpo/core/tor/-/issues/34357
> [Ticket #34357]: Reject Tor relays running the 0.4.1 series

- src/test/test_addr.c
> test: Add IPv6 test that suppose to fail on Windows

- changes/ticket40035
- src/lib/tls/tortls_nss.c
> NSS: Tell NSS that our SSL sockets are nonblocking.

- src/feature/nodelist/nodelist.c
Found by coverity with CID 1465290. Fix unreleased code.
Fixes #40049
> nodelist: Fix possible NULL deref

- src/app/config/resolve_addr.c
> relay: Limit Directory Authority Addresses to Address and ORPort

- src/app/config/fallback_dirs.inc
They are about to be shutdown in September.
> fallbackdir: Remove all three Digitalcourage3 relays

- changes/ticket33812
- src/feature/stats/bw_array_st.h
- src/feature/stats/bwhist.c
- src/feature/stats/bwhist.h
- src/feature/stats/include.am
- src/test/test_stats.c
Rebase of #2040 with signed commits.
> Ticket#33812 redux rebase

- .appveyor.yml
> CI: Remove VS2015 AppVeyor build [044 and onwards]

- src/feature/nodelist/routerlist.c
Instead of looking at the "Address" option alone, instead check if we have an
address in our cache (that is discovered by tor). If not, then it tells us
that tor does not have an address to work with so we can then ask a directory
authority for a suggestion.
Related #2178
> relay: Query our cache when deciding for dummy descriptor fetch

- changes/ticket40135
- src/feature/hs_common/shared_random_client.c
> srv: Remove spammy debug log

- src/app/main/subsysmgr.c
> main: Off by one when dumping subsystem list

- changes/bug40177
- src/lib/metrics/metrics_store.c
Fixes #40177; bugfix on 0.4.5.1-alpha.
> Fix another duplicate typedef.

- changes/bug30187
- configure.ac
- src/lib/thread/compat_winthreads.c
- src/lib/thread/threads.h
Fix bug where running a relay on Windows would use 100% CPU
after some time. Makes Windows >= Vista the required Windows
version to build and run tor.
> [Tor Gitlab #30187]: Fix 100% CPU usage on Windows relays

- .gitlab-ci.yml
- src/core/or/include.am
> or: Missing .inc file in include.am
